### ISSUE TITLE
Crash on malformed batch file  

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [ccsb-scripps/AutoDock-GPU#100]
Hi,

AutoDock-GPU currently doesn't handle properly malformed batch file and crashes with a segfault.

To reproduce, you can use the provided batch file [batchfile_bad.txt](https://github.com/ccsb-scripps/AutoDock-GPU/files/5104044/batchfile_bad.txt) (the `pdbqt` files have been mistakenly used instead of the `maps.fld` for the proteins).

The crash is caused by this code snippet:
https://github.com/ccsb-scripps/AutoDock-GPU/blob/d3bed224db27fa4ddbcadfa0c4781892e34dc0f1/host/src/getparameters.cpp#L99-L102

`filelist.fld_files.size()-1` can be `-1` on malformed batch which starts with a `pdbqt` file because `filelist.fld_files` would be empty.

Best regards,
Rémi

**Comment by atillack** [comment]
@RemiLacroix-IDRIS Thank you for the bug report and pointing exactly to where it is.

**Comment by atillack** [comment]
@RemiLacroix-IDRIS Fix is merged and that part of the code had another potential segfault that is fixed now too :-) Thank you again for pointing us towards it.

**Comment by RemiLacroix-IDRIS** [comment]
Thanks for fixing the issue.
