### ISSUE TITLE
How to install and use it on HPC?

### ISSUE THREAD

**Issue by hima111997** [ccsb-scripps/AutoDock-GPU#108]
Hi!
I read the usage part on github but I could not understand what (protein).maps.fld mean?

I want to use Autodock-GPU for virtual screening and from my experience with the normal version there should be a conf file and the ligands and protein should be in pdbqt format.

can you tell me how to use it for virtual screening?

Thanks

**Comment by diogomart** [comment]
Hi,

You need to precalculate the maps using autogrid, see here: https://ccsb.scripps.edu/autodock/autodock4/

Then, autodock-gpu reads the maps, not the protein .pdbqt file.

For ready to run examples, including the maps and .fld files, see here: https://github.com/diogomart/AD-GPU_set_of_42

Best regards,
