### ISSUE TITLE
Long GRID_PARAMETER_FILE paths in maps.fld and .maps files cause crash

### ISSUE THREAD

**Issue by JohnRyanAudio** [ccsb-scripps/AutoDock-GPU#109]
I have successfully run a screen of ~6000 ligands against a single receptor, but I am now experiencing a problem when running the same command with a different set of 460 ligands. I'm preparing the batch files the exact same way for both runs, using a script, and the only difference I see between the .gpf and .fld files are two atom types, F and Cl, have their positions swapped in the ligand_types and map sections of the files. I assume this is inconsequential. 

My command looks like this:
`~/AutoDock-GPU/bin/autodock_gpu_64wi -filelist batch.txt, -nrun 10 -lsmet ad -devnum 1 -xmloutput 0`

And my output is:
```
Running 460 jobs in pipeline mode
AutoDock-GPU version: v1.3

CUDA Setup time 0.277130s
(Thread 0 is setting up Job 0)
*** stack smashing detected ***: <unknown> terminated                                                   
Aborted (core dumped)
```
I have also tried compiling with 128wi, and executing with various parameter values--including full default.
The GPU is a Geforce GTX 1650 (I have 6 on this particular server, which is why I'm specifying -devnum), CUDA Version is 10.1, Ubuntu is the OS.
I don't currently have the ability to install systemd-coredump and I don't know if there is any other way to retrieve the core dump information from AutoDock-GPU, but I may be able to do this at a later time if it is necessary.

I'm quite confused since I am able to run a screen of >10x the number of ligands just fine, but this is crashing. Any help is appreciated.

UPDATE:
I tried to run this set of 460 on 4 other servers, which are running Geforce GTX 1050 and GeForce GTX 1060 GPUs, and they all result in the same "stack smashing detected" error. I also went on to run the other sets of compounds from the same library (I split the library into 6 parts, one for each GPU) and all of them ended up with the same result. Yet, another library prepared with the same receptor still works just fine.

**Comment by L30nardoSV** [comment]
Hi @JohnRyanAudio,

Many thanks for reporting. 

Can you share a minimum setup (ligand/receptor files, commands, etc) that results in the above failure so we can try reproducing it on our side?

**Comment by JohnRyanAudio** [comment]
Just late last night I discovered the cause of the problem.
The eleventh line of the .maps.fld file is a comment line that looks like:
`#GRID_PARAMETER_FILE /path/to/file.gpf`
and the first line of every .map file looks like:
`GRID_PARAMETER_FILE /path/to/file.gpf`

My /path/to/file.gpf is 148 characters long, resulting in a 168 or 167 character line for the given two files, respectively. I removed these lines from the .fld file and every .map file, and AutoDock-GPU ran succesfully. The reason why the first set did not crash is because I prepared it in a different part of my filesystem with a shorter path.

I still consider this a bug, as I would expect where I prepare my files to not have any effect on my ability to run AutoDock-GPU; even more so when the line in question is not even required. I will edit the title of this issue to articulate what I've found.

**Comment by L30nardoSV** [comment]
Hi @JohnRyanAudio, I was able to reproduce it by using a long `/path/to/file` path, just as you described.

Likely, this happens when parsing the grid-related files [here](https://github.com/ccsb-scripps/AutoDock-GPU/blob/develop/host/src/processgrid.cpp#L28). I will check it in more details as soon as possible, and come back to you.

**Comment by atillack** [comment]
@JohnRyanAudio The current PR #112 should fix the issue :-) Please test ...

**Comment by JohnRyanAudio** [comment]
I apologize for not being able to test, I didn't have a good opportunity to do so. The PR looks good, though, and I will have another screen in the near future with long filepaths, so I can use the fix you've implemented. Thank you.
