### ISSUE TITLE
AutodockZn forcefield with Autodock GPU

### ISSUE THREAD

**Issue by debanjansen48** [ccsb-scripps/AutoDock-GPU#113]
In my ongoing project I have a metal (Zn) containing protein. That Zn is impotent. I prepared grid map using Autogrid, which generate name.C.map, name.D.map, name.e.map, name.HD.map,name.maps.fld, name.maps.xyz, name.N.map, name.OA,maps,name.SA.map. During run autodock-gpu ask for name.A.map. name.S.maps and stop docking.. However in no case auto grid generated that. how to get that?? or resolve the issue?

My ligand library possess some Boron (B) containing molecules. I want to use AutodockZn force field with  Autodock GPU how to do that?

The dlg file not reporting Ki value. How to get that?

how to use Genetic algorithm instead of LGA run?

it reports same rmsd 0.00 for two or more than two ranks.

thanks

**Comment by L30nardoSV** [comment]
Hi @debanjansen48, for using the Genetic Algorithm instead of the LGA, you can provide this command option: `-lsrat 0.0` (which disables local search).

For your questions on AutoDockZn, maybe @diogomart has some suggestions?

**Comment by diogomart** [comment]
Hi @debanjansen48,
 
It is possible to use autodock4zn with AD-GPU. Simply follow the autodock4zn protocol and use AD-GPU instead of autodock4 http://autodock.scripps.edu/resources/autodockzn-forcefield

Further notes:
 - for Boron you'll need a Boron map, the easiest trick is to pretend it's Carbon, by copying name.C.map to name.B.map
 - not using local search easily leads to bad results
 - interpreting docking scores as Ki values may or may not be a good idea. In any case, see http://autodock.scripps.edu/faqs-help/faq/how-autodock-4-converts-binding-energy-kcal-mol-into-ki
 - you can edit the autogrid configuration file (GPF) to make autogrid write the maps for all the atom types you need
 - not sure what you mean by "it reports same rmsd 0.00 for two or more than two ranks"

**Comment by debanjansen48** [comment]
Thanks,  @Diogo


"*It is possible to use autodock4zn with AD-GPU. Simply follow the
autodock4zn protocol and use AD-GPU instead of autodock4
http://autodock.scripps.edu/resources/autodockzn-forcefield
<http://autodock.scripps.edu/resources/autodockzn-forcefield>*"

sir, for virtual screening using AD-GPU i generally use following protocol
1. In a folder i put all optimised ligand structure in pdbqt format with
.pdbqt extension and prepare a list of them (ls *.pdbqt > liglist.txt)
2. In the same folder I use to place all map files and append the
name.map.fld file  into the liglist.txt file  followed by ading "./"
symbols in the starting of the name.maps.fld file name. In addition, I will
copy the c.map file and rename it B.map file.
3. Than from that folder using terminal i run AD-GPU by using following
command
autodock_gpu_256 -filelist liglist.txt -nrun 50 -lsmet sw --xmloutput 0

i am planning to change it to
*autodock_gpu_256 -filelist liglist.txt -nrun 50 -lsrat 0.0 --xmloutput 0*
(is that ok?)

Sir, as i understood as per the protocol given in (
http://mgldev.scripps.edu/AutoDockZN/AutoDockZN_userguide.pdf) , it is
required to change last  command
autodock4 -p ligand_protein_tz.dpf -o ligand_protein_tz.dlg
to > autodock_gpu_256 -p ligand_protein_tz.dpf -o ligand_protein_tz.dlg

that will dock a single ligand

for vs probable I need prepare_gpf4zn.py, repare_dpf42.py, zinc_pseudo.py,
prepare_dpf42.py,AD4Zn.dat files, i am not sure...

so, as i understood I need to  prepare the protein as per AutodockZn
protocol and a sample gpf dpf file followed by map file
(1. $MGLROOT/bin/pythonsh prepare_receptor4.py -r protein.pdb -o
protein.pdbqt #> prepare protein
2. $MGLROOT/bin/pythonsh prepare_ligand4.py -l ligand.mol2 -o ligand.pdbqt
-A hydrogens #> prepare a sample ligand (co crystal ligand if present)
3. $MGLROOT/bin/pythonsh zinc_pseudo.py -r protein.pdbqt -o
protein_tz.pdbqt #> (modified protein)
4. MGLROOT/bin/pythonsh prepare_gpf4zn.py -l ligand.pdbqt -r
protein_tz.pdbqt -o protein_tz.gpf -p npts=40,30,50 -p gridcenter=18,134,-1 –p
parameter_file=AD4Zn.dat #>grid parameter file generation with ADTZn ff.
5. Then I run autogrid to generate map files #>generate mapfiles
6. using the mapfiles then i need to run AD-GPU. (autodock_gpu_256
-filelist liglist.txt -nrun 50 -lsmet sw --xmloutput 0)

Am I correct sir?

Regards
Debanjan

**Comment by debanjansen48** [comment]
**not sure what you mean by "it reports same rmsd 0.00 for two or more than two ranks"**

___________________________________________________________________
     |      |      |           |         |                 |
Rank | Sub- | Run  | Binding   | Cluster | Reference       | Grep
     | Rank |      | Energy    | RMSD    | RMSD            | Pattern
_____|______|______|___________|_________|_________________|___________
   1      1      2      -10.03      **0.00**     20.02           RANKING
   2      1      4       -9.51      **0.00**     18.52           RANKING
   3      1      7       -9.18      **0.00**     18.19           RANKING
   4      1      1       -9.11      **0.00**     19.27           RANKING
   5      1      6       -8.40      **0.00**     18.52           RANKING
   6      1      9       -8.33      **0.00**     19.89           RANKING
   7      1      8       -8.27      **0.00**     20.04           RANKING
   8      1     10       -8.02      **0.00**     18.79           RANKING
   8      2      3       -6.33         1.95        19.64           RANKING
   9      1      5       -7.32      **0.00**     19.67           RANKING

**Comment by debanjansen48** [comment]
CLUSTERING HISTOGRAM
    ____________________
**"it reports same rmsd 0.00 for two or more than two ranks"** following results are ok or have some issues?

________________________________________________________________________________
     |           |     |           |     |
Clus | Lowest    | Run | Mean      | Num | Histogram
-ter | Binding   |     | Binding   | in  |
Rank | Energy    |     | Energy    | Clus|    5    10   15   20   25   30   35
_____|___________|_____|___________|_____|____:____|____:____|____:____|____:___
   1 |    -11.85 |   2 |    -11.85 |   1 |#
   2 |    -11.51 |  10 |    -11.49 |   2 |##
   3 |    -11.40 |   9 |    -11.21 |   5 |#####
   4 |    -11.37 |   8 |    -11.37 |   1 |#
   5 |    -10.91 |   3 |    -10.91 |   1 |#
_____|___________|_____|___________|_____|______________________________________


    RMSD TABLE
    __________


_____________________________________________________________________
     |      |      |           |         |                 |
Rank | Sub- | Run  | Binding   | Cluster | Reference       | Grep
     | Rank |      | Energy    | RMSD    | RMSD            | Pattern
_____|______|______|___________|_________|_________________|___________
   1      1      2      -11.85      0.00     16.93           RANKING
   2      1     10      -11.51      0.00     16.44           RANKING
   2      2      6      -11.48      0.10     16.45           RANKING
   3      1      9      -11.40      0.00     16.53           RANKING
   3      2      1      -11.38      0.17     16.56           RANKING
   3      3      4      -11.10      0.35     16.69           RANKING
   3      4      7      -11.09      1.47     17.11           RANKING
   3      5      5      -11.06      1.17     17.06           RANKING
   4      1      8      -11.37      0.00     17.02           RANKING
   5      1      3      -10.91      0.00     17.93           RANKING

**Comment by diogomart** [comment]
Hi,

The values in `Cluster RMSD` are the RMSD from the best pose within each cluster. The best pose has zero RMSD from itself, so the zeros are expected.

`-lsrat 0.0` does not work very well. Large values are preferred (e.g. `-lsrat 100`).

**Comment by diogomart** [comment]
Closing, feel free to reopen if needed.
