### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by ungsik** [ccsb-scripps/AutoDock-GPU#116]
In the processligand.cpp,
https://github.com/ccsb-scripps/AutoDock-GPU/blob/8fea425af17bc2b41500a02502d33adc97df12d5/host/src/processligand.cpp#L540
upper bound of atom_id1 is number_of_atoms -1.
All diagonal elements of myligand->bonds is 1.
But the last bonds[number_of_atoms-1][number_of_atoms-1] is zero, because of the -1 in the atom_id1 bound.
Is it intended?

**Comment by atillack** [comment]
Thank you @ungsik. You have a keen eye :-) Fortunately, this is more of an algorithmic quirk than a bug.

The `bonds` array is used solely to determine wether atoms interact based on how many bonds they are separated by - this then gets stored in `myligand->intraE_contributors` (around line 200 in processligand.cpp is where this code starts). The value in `bonds[i][i]` has no influence on `intraE_contributors` as it is always set to zero for same atom indices.

That said, it is safe to add a one in line 542 in process_ligand.cpp (`atom_id2=atom_id1+1`) which safes a little bit of CPU time and is also already in an upcoming PR for a new feature :-)
