### ISSUE TITLE
Unable to compile 

### ISSUE THREAD

**Issue by parazue** [ccsb-scripps/AutoDock-GPU#120]
(base) msr@msr:~/Downloads/AutoDock-GPU-develop$ make DEVICE=CUDA NUMWI=256
make: git: Command not found
DEVICE is set to GPU
 
CPU_INCLUDE_PATH is undefined
CPU_LIBRARY_PATH is undefined
 
GPU_INCLUDE_PATH is set to /usr/local/cuda-10.2/include
GPU_LIBRARY_PATH is set to /usr/local/cuda-10.2/lib64
 
nvcc -DN256WI  -use_fast_math --ptxas-options="-v" -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -std=c++11 -I./common -I./host/inc -I/usr/local/cuda-10.2/include -I./cuda  -c ./cuda/kernels.cu
In file included from /usr/local/cuda-10.2/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.2/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
make: *** [Makefile.Cuda:183: kernels] Error 1

**Comment by diogomart** [comment]
Hi,

It seems your `CUDA` version is not compatible with your `gcc` version

> gcc versions later than 8 are not supported!

You could try OpenCL
`make DEVICE=OCLGPU`

**Comment by diogomart** [comment]
Closing, feel free to reopen if needed.
