### ISSUE TITLE
Random Seed

### ISSUE THREAD

**Issue by MherMatevosyan** [ccsb-scripps/AutoDock-GPU#126]
Hi,

How can I specify the random seed for Autodock GPU?

**Comment by atillack** [comment]
@MherMatevosyan With the `-seed` command line - it accepts up to three seeds separated by a comma. For example, `-seed  42` or `-seed 42,47,37` are all valid command line options.

**Comment by MherMatevosyan** [comment]
Thank you for your answer! Btw, what each seed number controls for?

**Comment by atillack** [comment]
You're welcome! The seeds are for initializing the random number generator (RNG) and additional seeds add a little bit more entropy and could be used, for example, to have different random numbers from a sequence, i.e. `-seed 12,0`, `-seed 12,1`, and `-seed 12,2` all would lead to different random numbers.

By default when AD-GPU starts, the first two seeds are set to the system time and the process id (the third one is unused, aka set to zero).

Although the seeds can be used to have identical results as the RNGs we are using are deterministic (i.e. produce the same sequence of random numbers given the same seeds) this is not necessarily the case all the time. When running things in parallel the sequence of random numbers - even with the same seeds - can diverge when worker threads using them are run out-of-order, which can easily happen on a GPU when running more work units than compute units or when using different GPUs. This is not a bug at this point but more a "potential future feature" :-)
