### ISSUE TITLE
XML file broken

### ISSUE THREAD

**Issue by Vardanos** [ccsb-scripps/AutoDock-GPU#127]
Hey, we wrote a script to extract the energies from the XML output.
But after your recent commit 06210141c8d3b8b60966a19472bd2e4f826b49ae the XML file generated by the AutoDock-GPU appears to have multiple roots:
`<autodock_gpu...>`
`<result...>`
Because of this XML parsing libraries fail to parse it.
Is this the way the output is supposed to be? Or should we develop our own workaround?

**Comment by atillack** [comment]
@Vardanos Thank you for your message - the XML file output currently is a bit in flux but should be final after PR #128. The main root now is `<autodock_gpu>` which contains the `<result>` block and the new ones.

**Comment by atillack** [comment]
PR #128 is merged and with it I am closing the issue :-) Please reopen if you feel it necessary.
