### ISSUE TITLE
Error while performing autodock

### ISSUE THREAD

**Issue by PabloIriso** [ccsb-scripps/AutoDock-GPU#140]
After running autodock4 in autodocktools I'm getting this in my .dlf file.

BEGINNING GENETIC ALGORITHM DOCKING 1 of 10
Run: 1 Seed: 1234900043 807448529 [ Run 1 of 10 GA/GALS ]
NOTE: All energies are equal in population; re-initializing. (Try Number 1)
NOTE: All energies are equal in population; re-initializing. (Try Number 2)
NOTE: All energies are equal in population; re-initializing. (Try Number 3)
NOTE: All energies are equal in population; re-initializing. (Try Number 4)
NOTE: All energies are equal in population; re-initializing. (Try Number 5)
NOTE: All energies are equal in population; re-initializing. (Try Number 6)
NOTE: All energies are equal in population; re-initializing. (Try Number 7)
NOTE: All energies are equal in population; re-initializing. (Try Number 8)

What can I do to solve this?

I'm getting the same error for different ligands.

Found this: 

http://autodock.scripps.edu/faqs-help/how-to/fixing-all-energies-are-equal-in-population-re-initializing-message

However, I have no call_glss.cc file inside my autodock repositories

**Comment by diogomart** [comment]
That message is specific to autodock4, which is not autodock-gpu. They are different programs that use the same scoring function.

I recommend to use autodock-gpu instead of autodock4, or even [vina](https://github.com/ccsb-scripps/AutoDock-Vina) which now supports the autodock4 scoring function.

**Comment by diogomart** [comment]
Closing, feel free to re-open if needed.

**Comment by PabloIriso** [comment]
Thanks Diego
