### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70'/Makefile.Cuda:183: recipe for target 'kernels' failed

### ISSUE THREAD

**Issue by amir-tagh** [ccsb-scripps/AutoDock-GPU#144]
Hello,

I am trying to install the autodock on my machine (precision 3630) with  a Quadro P620 card. I have made the changes in bashrc as following:

export GPU_INCLUDE_PATH=/usr/local/cuda-8.0/include
export GPU_LIBRARY_PATH=/usr/local/cuda-8.0/lib64

using the following command:
make DEVICE=CUDA NUMWI=1

i get the following error:

DEVICE is set to GPU
 
CPU_INCLUDE_PATH is undefined
CPU_LIBRARY_PATH is undefined
 
GPU_INCLUDE_PATH is set to /usr/local/cuda-8.0/include
GPU_LIBRARY_PATH is set to /usr/local/cuda-8.0/lib64
 
nvcc -DN64WI  -use_fast_math --ptxas-options="-v" -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -std=c++11 -I./common -I./host/inc -I/usr/local/cuda-8.0/include -I./cuda  -c ./cuda/kernels.cu
nvcc fatal   : Unsupported gpu architecture 'compute_70'
Makefile.Cuda:183: recipe for target 'kernels' failed
make: *** [kernels] Error 1

can you please help with the error.

Best,
Amir

**Comment by atillack** [comment]
@amir-tagh Hello Amir! 

You can explicitly compile for a specific target architecture like so: `make DEVICE=CUDA NUMWI=64 TARGETS=61`

If you can, I would also recommend to upgrade to a newer Cuda version as there are some fixes and optimizations for the Pascal architecture in them.

Hope this helps!

P.S. You were using NUMWI=1 which will fall back to NUMWI=64 (the default) as only 32, 64, 128, and 256 are supported with the Cuda version.

**Comment by amir-tagh** [comment]
Hello Andreas,

Thanks a lot for your help. Using the command you suggested "make DEVICE=CUDA NUMWI=64 TARGETS=61" I am getting the following errors:

nvcc -DN64WI  -use_fast_math --ptxas-options="-v" -gencode arch=compute_61,code=sm_61 -std=c++11 -I./common -I./host/inc -I/usr/local/cuda-8.0/include -I./cuda  -c ./cuda/kernels.cu
./cuda/calcenergy.cu(449): error: identifier "__any_sync" is undefined

./cuda/calcenergy.cu(449): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(648): error: identifier "__any_sync" is undefined

./cuda/calcMergeEneGra.cu(648): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(649): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(650): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(657): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(661): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(662): error: identifier "__shfl_sync" is undefined

./cuda/calcMergeEneGra.cu(663): error: identifier "__shfl_sync" is undefined

./cuda/kernel2.cu(46): error: identifier "__any_sync" is undefined

./cuda/kernel2.cu(46): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(80): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(80): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(80): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(80): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(80): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(104): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(104): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(104): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(104): error: identifier "__shfl_sync" is undefined

./cuda/kernel4.cu(104): error: identifier "__shfl_sync" is undefined

22 errors detected in the compilation of "/tmp/tmpxft_00006514_00000000-7_kernels.cpp1.ii".
Makefile.Cuda:183: recipe for target 'kernels' failed
make: *** [kernels] Error 2

###########################################
there is some discrepancy between nvidia-smi and nvcc --version on my machine that I will try to fix

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:01:00.0 Off |                  N/A |
| 34%   48C    P0    N/A /  N/A |   1408MiB /  2000MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
 ##########################################################

 Thanks in forward.

Best,

**Comment by atillack** [comment]
@amir-tagh  Thank you for posting your error messages: they made me realize we list Cuda 8 as supported which is not true as __shfl_sync and __any_sync were introduced in Cuda 9 ... I will fix this in the documentation.

Updating your Cuda SDK to what the driver supports (Cuda 10) will fix those issues.
