### ISSUE TITLE
./host/inc/performdocking.h:32:10: fatal error: cuda.h: No such file or directory

### ISSUE THREAD

**Issue by amir-tagh** [ccsb-scripps/AutoDock-GPU#149]
Hello,

I am trying to install Auto-dock GPU (make DEVICE=CUDA NUMWI=64) and I get the following error:

In file included from ./host/src/main.cpp:37:0:
./host/inc/performdocking.h:32:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
OS is Ubuntu 18.04
Cuda compilation tools, release 10.1, V10.1.243

I appreciate your help to resolve the issue.

Best,
Amir

**Comment by diogomart** [comment]
Hello Amir,

Did it print the following? If yes please see https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Guideline-for-users
```
GPU_INCLUDE_PATH is undefined
GPU_LIBRARY_PATH is undefined
```
Best regards,

**Comment by amir-tagh** [comment]
Hello Diogo,

I added the following lines to the bashrc file and problem solved. Thanks for your help.

export GPU_INCLUDE_PATH=/usr/local/cuda-10.1/include
export GPU_LIBRARY_PATH=/usr/local/cuda-10.1/lib64

Best,
Amir

**Comment by diogomart** [comment]
Great! :)
