### ISSUE TITLE
A receptor.maps.fld for every ligand?

### ISSUE THREAD

**Issue by matiaszunigabustos** [ccsb-scripps/AutoDock-GPU#150]
Hi! Im preparing a docking using a receptor and multiple ligands, each with different atom types. I understand that maps.fld file contains the information of the atomic composition of the receptor and the ligand. My question is, Do I have to do a different map.fld file for every ligand separate? I tried to make a "general" fld file including all types of atoms contained in the ligands but when I ran the docking I got and error. 

Thanks!!

**Comment by diogomart** [comment]
Hi!

The general FLD file is a good idea and it should work. What error did you get?

**Comment by matiaszunigabustos** [comment]
Hi! I prepared a general FLD file again and it works.

Thanks

**Comment by YoBismarck20** [comment]
Hi there!
I am sorry to disturb but would you mind elaborating on what is a "general FLD" file and how to generate it? I am facing similar issues and I would like to know how to solve it.

Thanks!

**Comment by matiaszunigabustos** [comment]
Hi! We refer a general FLD as a file that contains all atom types of the ligands, or the atoms that we want. I generated a gpf file for a X ligand, then I add more atom types in "ligand_types" section of the file. You can see them in  "http://autodock.scripps.edu/faqs-help/faq/faqsection_view?section=Scientific%20Questions" on "Where do I set the AutoDock 4 force field parameters?" section.  Then I add the corresponding map outputs below and I ran autogrid4 with the modified gpf file.

**Comment by YoBismarck20** [comment]
So, in the simplest sense, you are going to generate a GPF for all ligands and then append the unique atom types into one big gpf file?

**Comment by diogomart** [comment]
I use this script for writing general GPFs -> [write-gpf.py.zip](https://github.com/ccsb-scripps/AutoDock-GPU/files/6910405/write-gpf.py.zip)

Probably we should update the documentation and create general GPF by default.
