### ISSUE TITLE
GpuData.h unavailable

### ISSUE THREAD

**Issue by shutUpAndCompute** [ccsb-scripps/AutoDock-GPU#156]
All lib64 and include variables/paths and device CUDA, including lib64 in extra folder have been set in .bashrc on manjaro. Compilation using make DEVICE=GPU starts but fails at 

In file included from ./host/src/main.cpp:40:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No such file or directory
   47 | #include "GpuData.h"

Any resolution?

**Comment by diogomart** [comment]
"GpuData.h" is here: https://github.com/ccsb-scripps/AutoDock-GPU/tree/develop/cuda

Is your local repository up to date?

**Comment by shutUpAndCompute** [comment]
Yes, its updated locally and I can see the file. .bashrc has following entries pointing to latest CUDA version 11.x
 export PATH="/opt/cuda/bin:$PATH"
 export CPATH="/opt/cuda/include:/opt/cuda/extras/CUPTI/include/:$CPATH"
 export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/cuda/lib64:/opt/cuda/extras/CUPTI/lib64/
 export GPU_INCLUDE_PATH="/opt/cuda/include:/opt/cuda/extras/CUPTI/include/:$CPATH"
 export GPU_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/cuda/lib64:/opt/cuda/extras/CUPTI/lib64/
 export CUDA_VISIBLE_DEVICES=1



AND error log still seems to not find PATHS

DEVICE is set to GPU
 
CPU_INCLUDE_PATH is undefined
CPU_LIBRARY_PATH is undefined
 
GPU_INCLUDE_PATH is undefined
GPU_LIBRARY_PATH is undefined
 
nvcc -DN128WI  -use_fast_math --ptxas-options="-v" -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -std=c++11 -I./common -I./host/inc -I -I./cuda  -c ./cuda/kernels.cu
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_52'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_52'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 13 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 36 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_60'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_60'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 13 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 36 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_61'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_61'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 13 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 36 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_70'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 384 bytes cmem[0]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_70'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 15 registers, 4 bytes smem, 352 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 368 bytes cmem[0]
ln -sf performdocking.h.Cuda ./host/inc/performdocking.h
ln -sf performdocking.cpp.Cuda ./host/src/performdocking.cpp
Building autodock_gpu_128wi ...
g++ \
./host/src/calcenergy.cpp ./host/src/getparameters.cpp ./host/src/main.cpp ./host/src/miscellaneous.cpp ./host/src/performdocking.cpp ./host/src/processgrid.cpp ./host/src/processligand.cpp ./host/src/processresult.cpp ./host/src/setup.cpp \
-std=c++11 -I./common -I./host/inc -I -I./cuda -L -Wl,-rpath=: -DVERSION=\"v1.5.2-1-ga917c4828b612310fd9319eb1c95aa65133d6c52\" \
kernels.o -lcurand -lcudart  \
-o./bin/autodock_gpu_128wi \
-DGPU_DEVICE -DN128WI  -O3   
In file included from ./host/src/main.cpp:40:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No such file or directory
   47 | #include "GpuData.h"
      |          ^~~~~~~~~~~
compilation terminated.
In file included from ./host/src/performdocking.cpp:34:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No such file or directory
   47 | #include "GpuData.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile.Cuda:199: odock] Error 1

**Comment by diogomart** [comment]
Looks like `g++` ignores the `./cuda` folder because there are two consecutive `-I -I`.
```
-I -I./cuda
```
This will be solved if `GPU_INCLUDE_PATH` and `GPU_LIBRARY_PATH` are defined.

Please see: https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Guideline-for-users

**Comment by shutUpAndCompute** [comment]
Set the paths as in the guidelines that solved some library issues. Thereafter it could not local opencl libraries that I had installed using pacman. Had to use yay package manager to install intel-opencl libraries. Compiled after that.  Many Thanks.

**Comment by shutUpAndCompute** [comment]
Closing thread with thanks.
