### ISSUE TITLE
System consists of too many atoms and dpf tokens 

### ISSUE THREAD

**Issue by stikeleather** [ccsb-scripps/AutoDock-GPU#157]
When I try to start a docking calculation, I get this error: "System consists of too many atoms. Maximum number of atoms is 256." I am executing the command with the --ffile and --lfile flags.

It seems no matter what I change in my .gpf file before performing autogrid4, it doesn't affect the number of atoms in the system. The only thing that has worked to reduce the atom count has been going into pymol and deleting atoms from my .pdb file. But even after drastically trimming the protein down, I am still at 774 atoms. It doesn't seem right that I would have to manually delete atoms before passing the receptor to AutoDock-GPU. 

Additionally, when I've tried to execute with the -I flag (for dpf) I get the error: "Unknown or unsupported dpf token." This may be related to having too many atoms, but that error message should be more clear in that case. 

1) Is it possible to increase the maximum number of atoms allowed in the system?

2) Is it possible to reduce the number of atoms in the system by adding flags to gpf file generation and/or autogrid4?

3) What's the proper method for decreasing atom counts below the maximum?

4) What does the dpf token error mean?

Thanks for your help

**Comment by diogomart** [comment]
The maximum number of atoms is for the ligand, not for the receptor. AutoDock-GPU does not read the receptor, it reads only the maps and the FLD file (which are written by autogrid).

A token is a keyword, so the DPF file has some text that shouldn't be there.

**Comment by stikeleather** [comment]
Thanks for your reply. I have been able to successfully execute using the --ffile and --lfile flags. The problem was my fault: I accidentally pointed the --llfile flag at my receptor. 

Still having issues with the DPF files though, I am attaching one of my DPF files here. Maybe you could let me know what the issue with it is. I've compared it to the documentation, and I'm not seeing the problem. It normally has the .dpf extension (changed here to .txt to upload). 
[ZINC000001648371.txt](https://github.com/ccsb-scripps/AutoDock-GPU/files/7325019/ZINC000001648371.txt)

**Comment by diogomart** [comment]
It should print which token is not being recognized. It's probably `autodock_parameter_version`.

In general, it's better to avoid DPF files, because autodock-gpu has only partial support for those.

**Comment by stikeleather** [comment]
It was that autodock_parameter_version line that was the issue. Thank you for your help.
