### ISSUE TITLE
Final Intermolecular Energy is zero for all docked molecules

### ISSUE THREAD

**Issue by ghost** [ccsb-scripps/AutoDock-GPU#159]
The Final Intermolecular energy value after docking is zero, making the binding energy positive. This is happening to the entire batch of ligands. 

Is there a way to resolve this?

Many thanks!

**Comment by diogomart** [comment]
Need more information to be able to help.

Best regards,

**Comment by ghost** [comment]
Thanks @diogomart 
It was a fault in the ligand files.

Thanks again !
