### ISSUE TITLE
 warning: format ‘%d’ expects argument of type ‘int’

### ISSUE THREAD

**Issue by eneas77** [ccsb-scripps/AutoDock-GPU#162]
When compiling via make DEVICES=CUDA

there are a couple of bugs appearing in the compilation:

1) ./host/src/processgrid.cpp:150:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wformat=]

2) In file included from ./host/src/main.cpp:40:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No existe el archivo o el directorio
   47 | #include "GpuData.h"

My ./bashrc has the following lines:

export GPU_INCLUDE_PATH=/usr/include/CL
export GPU_LIBRARY_PATH=/usr/lib/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=/usr/lib/usr/lib/x86_64-linux-gnu
export CUDA_VISIBLE_DEVICES=1

Compilation stops without generating any output in the bin folder. Any insights around this?

Thanks

**Comment by diogomart** [comment]
Hi, the GpuData.h issue happened before, please see: https://github.com/ccsb-scripps/AutoDock-GPU/issues/156

**Comment by eneas77** [comment]
Hi, already GPU_INCLUDE_PATH and GPU_LIBRARY_PATH are defined. No differences at all, i´m afraid....

**Comment by atillack** [comment]
@eneas77 What operating system are you on? Which version of Cuda is installed?

It looks like you are trying to compile the Cuda version but the include path in your post points to a directory that usually contains CL.h for OpenCL. In the case of OpenCL though, if there is a /usr/include/CL/CL.h file you would need to set `GPU_INCLUDE_PATH=/usr/include`.

For Cuda, on one of our machines for example, I usually use
`export GPU_INCLUDE_PATH=/usr/local/cuda/include`
`export GPU_LIBRARY_PATH=/usr/local/cuda/lib64`
These are the default Cuda directories for some Linux systems (sometimes, instead of `/usr/local/cuda` the version is appended, i.e. `/usr/local/cuda-11.2`)

Hope this helps and compilation will work for you :-)

**Comment by eneas77** [comment]
Hi,

SO is Ubuntu 20.04.3 LTS. Cuda is 460.106.00

After changing the lines to:

export GPU_INCLUDE_PATH=/usr/lib/cuda/include
export GPU_LIBRARY_PATH=/usr/lib/cuda/lib64

where cuda is stored, nothing changed. Still yielding the same bug...

**Comment by atillack** [comment]
@eneas77 Could you test if `nvcc --version` is working and double-check that your Cuda installation is indeed in `/usr/lib/cuda` rather than in `/usr/local/cuda`?

**Comment by eneas77** [comment]
Hi,

nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

whereis cuda returns
cuda: /usr/lib/cuda /usr/include/cuda.h

Cheers

**Comment by atillack** [comment]
@eneas77 Thank you. Could you try with:
`export GPU_INCLUDE_PATH=/usr/include`

For the `GPU_LIBRARY_PATH`, I would try `/usr/lib/cuda/lib64`, `/usr/lib/cuda`, `/usr/lib`, or `/usr/lib64`.

**Comment by diogomart** [comment]
This works on a local Ubuntu 20.04.3, after installing cuda with `sudo apt install nvidia-cuda-toolkit`  
```
export GPU_INCLUDE_PATH=/usr/include
export GPU_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
```

**Comment by eneas77** [comment]
Tried these alternatives, but failed.

Here is the extract of the output:

rm -f ./host/inc/performdocking.h ./host/src/performdocking.cpp
Building adgpu_analysis ...
g++ \
./host/src/calcenergy.cpp ./host/src/getparameters.cpp ./host/src/main.cpp ./host/src/miscellaneous.cpp ./host/src/processgrid.cpp ./host/src/processligand.cpp ./host/src/processresult.cpp ./host/src/setup.cpp \
-std=c++11 -I./common -I./host/inc -DVERSION=\"v1.5-release\" \
-o./bin/adgpu_analysis \
 -O3 -DTOOLMODE
./host/src/processgrid.cpp: In function ‘int get_gridinfo(const char*, Gridinfo*)’:
./host/src/processgrid.cpp:150:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
  150 |   printf("Error: Number of grid map labels (%d) and filenames (%d) mismatched in fld file.\n", grid_types, mygrid->grid_mapping.size()-grid_types);
      |                                                                ~^                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                 |                                                                     |
      |                                                                 int                                                                   std::vector<std::__cxx11::basic_string<char> >::size_type {aka long unsigned int}
      |                                                                %ld
./host/src/processligand.cpp: In function ‘float calc_interE_f(const Gridinfo*, const Liganddata*, float, int, float&, float*, float*, float*)’:
./host/src/processligand.cpp:1947:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1947 |    printf("x_low = %d, x_high = %d, x_frac = %f\n", x_low, x_high, x_frac);
      |                    ~^                               ~~~~~
      |                     |                               |
      |                     int                             double
      |                    %f
./host/src/processligand.cpp:1948:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1948 |    printf("y_low = %d, y_high = %d, y_frac = %f\n", y_low, y_high, y_frac);
      |                    ~^                               ~~~~~
      |                     |                               |
      |                     int                             double
      |                    %f
./host/src/processligand.cpp:1949:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1949 |    printf("z_low = %d, z_high = %d, z_frac = %f\n\n", z_low, z_high, z_frac);
      |                    ~^                                 ~~~~~
      |                     |                                 |
      |                     int                               double
      |                    %f
DEVICE is set to GPU

CPU_INCLUDE_PATH is undefined
CPU_LIBRARY_PATH is undefined

GPU_INCLUDE_PATH is undefined
GPU_LIBRARY_PATH is undefined

nvcc -DN64WI  -use_fast_math --ptxas-options="-v" -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -std=c++11 -I./common -I./host/inc -I -I./cuda  -c ./cuda/kernels.cu
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_52'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_52'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 14 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_52'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 40 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_60'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_60'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 14 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_60'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 40 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 336 bytes cmem[0], 112 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 336 bytes cmem[0], 120 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_61'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 352 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 336 bytes cmem[0], 48 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_61'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 14 registers, 4 bytes smem, 320 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_61'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 336 bytes cmem[0], 40 bytes cmem[2]
ptxas info    : 0 bytes gmem, 288 bytes cmem[3]
ptxas info    : Compiling entry function '_Z27gpu_gradient_minAdam_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z27gpu_gradient_minAdam_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7416 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z25gpu_gradient_minAD_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z25gpu_gradient_minAD_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 7428 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_' for 'sm_70'
ptxas info    : Function properties for _Z31gpu_gen_and_eval_newpops_kernelPfS_S_S_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3672 bytes smem, 384 bytes cmem[0]
ptxas info    : Compiling entry function '_Z21gpu_perform_LS_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z21gpu_perform_LS_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z20gpu_sum_evals_kernelv' for 'sm_70'
ptxas info    : Function properties for _Z20gpu_sum_evals_kernelv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 15 registers, 4 bytes smem, 352 bytes cmem[0]
ptxas info    : Compiling entry function '_Z23gpu_calc_initpop_kernelPfS_' for 'sm_70'
ptxas info    : Function properties for _Z23gpu_calc_initpop_kernelPfS_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 3076 bytes smem, 368 bytes cmem[0]
ln -sf performdocking.h.Cuda ./host/inc/performdocking.h
ln -sf performdocking.cpp.Cuda ./host/src/performdocking.cpp
Building autodock_gpu_64wi ...
g++ \
./host/src/calcenergy.cpp ./host/src/getparameters.cpp ./host/src/main.cpp ./host/src/miscellaneous.cpp ./host/src/performdocking.cpp ./host/src/processgrid.cpp ./host/src/processligand.cpp ./host/src/processresult.cpp ./host/src/setup.cpp \
-std=c++11 -I./common -I./host/inc -I -I./cuda -L -Wl,-rpath=: -DVERSION=\"v1.5-release\" \
kernels.o -lcurand -lcudart  \
-o./bin/autodock_gpu_64wi \
-DGPU_DEVICE -DN64WI  -O3
In file included from ./host/src/main.cpp:40:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No existe el archivo o el directorio
   47 | #include "GpuData.h"
      |          ^~~~~~~~~~~
compilation terminated.
In file included from ./host/src/performdocking.cpp:34:
./host/inc/performdocking.h:47:10: fatal error: GpuData.h: No existe el archivo o el directorio
   47 | #include "GpuData.h"
      |          ^~~~~~~~~~~
compilation terminated.
./host/src/processgrid.cpp: In function ‘int get_gridinfo(const char*, Gridinfo*)’:
./host/src/processgrid.cpp:150:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
  150 |   printf("Error: Number of grid map labels (%d) and filenames (%d) mismatched in fld file.\n", grid_types, mygrid->grid_mapping.size()-grid_types);
      |                                                                ~^                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                 |                                                                     |
      |                                                                 int                                                                   std::vector<std::__cxx11::basic_string<char> >::size_type {aka long unsigned int}
      |                                                                %ld
./host/src/processligand.cpp: In function ‘float calc_interE_f(const Gridinfo*, const Liganddata*, float, int, float&, float*, float*, float*)’:
./host/src/processligand.cpp:1947:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1947 |    printf("x_low = %d, x_high = %d, x_frac = %f\n", x_low, x_high, x_frac);
      |                    ~^                               ~~~~~
      |                     |                               |
      |                     int                             double
      |                    %f
./host/src/processligand.cpp:1948:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1948 |    printf("y_low = %d, y_high = %d, y_frac = %f\n", y_low, y_high, y_frac);
      |                    ~^                               ~~~~~
      |                     |                               |
      |                     int                             double
      |                    %f
./host/src/processligand.cpp:1949:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
 1949 |    printf("z_low = %d, z_high = %d, z_frac = %f\n\n", z_low, z_high, z_frac);
      |                    ~^                                 ~~~~~
      |                     |                                 |
      |                     int                               double
      |                    %f
make: *** [Makefile.Cuda:199: odock] Error 1

**Comment by atillack** [comment]
@eneas77 This is tantalizingly close to working (as the Cuda kernels already compiled)... From the output it looks like GPU_INCLUDE_PATH and GPU_LIBRARY_PATH are not set. They need to be set in the same shell that you are running the `make` command in.

**Comment by sisco0** [comment]
Kindly give a try to the https://github.com/ccsb-scripps/AutoDock-GPU/pull/174 _Pull Request_ with the command described in the comment. Hopefully, it would bring the expected output @eneas77.
