### ISSUE TITLE
Mismatched tag for XML output file

### ISSUE THREAD

**Issue by andreisfc** [ccsb-scripps/AutoDock-GPU#175]
On contact analysis, mismatched closing tag specifically for `contact_analysis_ligname` (reads `contact_analsyis_ligname`). E.g.:
`				<contact_analysis_ligname>   "H",   "H",   "O",   "H",   "H",   "H",   "C",   "C",   "C",   "C",   "C",   "C",   "C"</contact_analsyis_ligname>`

Consistent for all analyses performed under AutoDock-GPU v1.5-release on Linux Mint 20.2.

Edit: attached output example
[107.zip](https://github.com/ccsb-scripps/AutoDock-GPU/files/7934237/107.zip)

**Comment by atillack** [comment]
@andreisfc Thank you for finding this misspelling. I will fix it in the next PR ...
