### ISSUE TITLE
Astex Test files not found

### ISSUE THREAD

**Issue by sisco0** [ccsb-scripps/AutoDock-GPU#177]
**Describe the bug**
The _Makefiles_ for _CUDA_ and _OpenCL_ reference `./input_tsri/search-set-astex/$(ASTEX_PDB)/protein.maps.fld` for the _Astex_ test. These paths are not found in the current repository so these tests have been disabled in https://github.com/ccsb-scripps/AutoDock-GPU/pull/174 in https://github.com/ccsb-scripps/AutoDock-GPU/pull/174/commits/cfd0a2d360f26ee964fe512ad7a8ff8df69e32c0.

**To Reproduce**
Review the following lines of code for checking out the issue:
https://github.com/ccsb-scripps/AutoDock-GPU/blob/7b7d5ed516f870611a93b14e14c6b64023eccb14/Makefile.Cuda#L235-L243
https://github.com/ccsb-scripps/AutoDock-GPU/blob/7b7d5ed516f870611a93b14e14c6b64023eccb14/Makefile.OpenCL#L303-L311

**Expected behavior**
The input files should be present in the repository somehow.

**Information to help narrow down the bug**
- Which version of AutoDock-GPU are you using?
`develop` branch of `AutoDock-GPU` (this repository)
- Which operating system are you on?
_Ubuntu 20.10_
- As this error is referring a design error, no effort on filling runtime questions has been done.

**Comment by atillack** [comment]
@sisco0 Yes, those tests were internal tests during earlier stages of development and are going to be taken out of the Makefiles eventually.

**Comment by sisco0** [comment]
Thank you for the clarification.
