### ISSUE TITLE
Energy score difference between dlg/xml output and stdout output 

### ISSUE THREAD

**Issue by shouti-fredchang** [ccsb-scripps/AutoDock-GPU#178]
**Describe the bug**
When you run autodockgpu the stdout displays convergence of the energy terms and displays 'Best energy' over the generations.

However when you look in the dlg or xml file, I can not map 'Best energy' term from stdout to the energy terms within these output files.  Neither free_NRG_binding, final_intermol_NRG, etc. match the stdout energy terms.  

Question (or Bug?) what energy term is stdout printing?

Below are the outputs:

--STDOUT-------------------------
AutoDock-GPU version: v1.5.2-1-ga917c4828b612310fd9319eb1c95aa65133d6c52

Running 1 docking calculation

Cuda device:                              Tesla K80
Available memory on device:               11380 MB (total: 11441 MB)

CUDA Setup time 0.159015s

Running Job #1
    Using heuristics: (capped) number of evaluations set to 1613968
    Local-search chosen method is: ADADELTA (ad)

Rest of Setup time 0.019470s

Executing docking runs, stopping automatically after either reaching 0.15 kcal/mol standard deviation of
the best molecules of the last 4 * 5 generations, 42000 generations, or 1613968 evaluations:

Generations |  Evaluations |     Threshold    |  Average energy of best 10%  | Samples |    Best energy
------------+--------------+------------------+------------------------------+---------+-------------------
          0 |          150 | 7202.74 kcal/mol | 2331.32 +/- 1299.05 kcal/mol |       4 | 1187.14 kcal/mol
          5 |        38742 | 7202.74 kcal/mol |  747.52 +/- 1121.11 kcal/mol |     692 |   -8.20 kcal/mol
         10 |        81134 |  771.82 kcal/mol |  -11.51 +/-    0.18 kcal/mol |       4 |  -11.80 kcal/mol
         15 |       127329 |  -10.83 kcal/mol |  -11.64 +/-    0.21 kcal/mol |       8 |  -11.84 kcal/mol
         20 |       176807 |  -11.24 kcal/mol |  -11.54 +/-    0.18 kcal/mol |      11 |  -11.87 kcal/mol
         25 |       228675 |  -11.30 kcal/mol |  -11.77 +/-    0.13 kcal/mol |      10 |  -11.92 kcal/mol
         30 |       282194 |  -11.58 kcal/mol |  -11.77 +/-    0.11 kcal/mol |      23 |  -11.94 kcal/mol
         35 |       336417 |  -11.69 kcal/mol |  -11.84 +/-    0.07 kcal/mol |      17 |  -11.95 kcal/mol
         40 |       393667 |  -11.71 kcal/mol |  -11.84 +/-    0.08 kcal/mol |      22 |  -11.95 kcal/mol
         45 |       451665 |  -11.79 kcal/mol |  -11.90 +/-    0.04 kcal/mol |      20 |  -11.95 kcal/mol
------------+--------------+------------------+------------------------------+---------+-------------------

                                   Finished evaluation after reaching
                                  -11.83 +/-    0.10 kcal/mol combined.
                                82 samples, best energy   -11.95 kcal/mol.

Docking time 7.641588s

Shutdown time 0.000436s

Job #1 took 7.662 sec after waiting 0.494 sec for setup

Run time of entire job set (1 file): 8.243 sec
Processing time: 0.087 sec

All jobs ran without errors.
---------------------------

-----XML output-----------
<?xml version="1.0" ?>
<autodock_gpu>
	<version>v1.5.2-1-ga917c4828b612310fd9319eb1c95aa65133d6c52</version>
	<arguments>-L ob-GSBR-1002859R.pdbqt --gbest 1 -M ../grid/6x1a_prepped_dHet.maps.fld -N ob-GSBR-1002859R-gpudocked</arguments>
	<grid>../grid/6x1a_prepped_dHet.maps.fld</grid>
	<ligand>ob-GSBR-1002859R.pdbqt</ligand>
	<seed>1643738599 11344</seed>
	<ls_method>ad</ls_method>
	<autostop>yes</autostop>
	<heuristics>yes</heuristics>
	<run_requested>20</run_requested>
	<runs>
		<run id="2">
			<free_NRG_binding>   -8.00</free_NRG_binding>
			<final_intermol_NRG> -10.39</final_intermol_NRG>
			<internal_ligand_NRG>-1.56</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>19.284109 14.931024 12.331568</tran0>
			<axisangle0>-0.73783792 0.67207844 0.06249613 172.227982</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>200.173889 214.949631 177.946823 276.824768 218.018829 333.163818 155.610107 271.751190
			</dihe0>
		</run>
		<run id="12">
			<free_NRG_binding>   -8.00</free_NRG_binding>
			<final_intermol_NRG> -10.38</final_intermol_NRG>
			<internal_ligand_NRG>-1.59</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.072251 15.439766 11.701437</tran0>
			<axisangle0>-0.65655556 0.75153447 -0.06427088 186.751465</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>38.071114 231.912262 189.876968 261.287750 184.107788 296.017395 159.463501 309.531097
			</dihe0>
		</run>
		<run id="4">
			<free_NRG_binding>   -7.99</free_NRG_binding>
			<final_intermol_NRG> -10.38</final_intermol_NRG>
			<internal_ligand_NRG>-1.59</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>20.944377 15.393787 11.784851</tran0>
			<axisangle0>0.66395349 -0.74548609 0.05844875 177.340393</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>39.491718 229.252869 189.740967 260.362152 189.829620 299.250336 161.388168 303.151306
			</dihe0>
		</run>
		<run id="5">
			<free_NRG_binding>   -7.99</free_NRG_binding>
			<final_intermol_NRG> -10.37</final_intermol_NRG>
			<internal_ligand_NRG>-1.58</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>19.498823 15.760056 10.331765</tran0>
			<axisangle0>-0.70070818 0.70966951 -0.07332964 211.788528</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>215.506897 211.705124 178.929382 259.381439 180.844376 288.859009 158.205032 336.849030
			</dihe0>
		</run>
		<run id="10">
			<free_NRG_binding>   -7.97</free_NRG_binding>
			<final_intermol_NRG> -10.36</final_intermol_NRG>
			<internal_ligand_NRG>-1.61</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.164536 15.478552 11.601812</tran0>
			<axisangle0>-0.65287727 0.75385157 -0.07388566 186.980011</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>229.592743 234.167206 190.972168 256.583588 187.908539 294.466125 160.287415 311.156860
			</dihe0>
		</run>
		<run id="8">
			<free_NRG_binding>   -7.96</free_NRG_binding>
			<final_intermol_NRG> -10.34</final_intermol_NRG>
			<internal_ligand_NRG>-1.61</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.038280 15.431891 11.880082</tran0>
			<axisangle0>0.65926691 -0.74925462 0.06312406 175.855347</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>223.985565 240.307098 190.154144 259.352631 188.885986 293.548645 159.781235 305.001648
			</dihe0>
		</run>
		<run id="17">
			<free_NRG_binding>   -7.92</free_NRG_binding>
			<final_intermol_NRG> -10.31</final_intermol_NRG>
			<internal_ligand_NRG>-1.56</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>19.550915 15.880111 9.966114</tran0>
			<axisangle0>-0.69250042 0.71433224 -0.10085936 216.708939</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>29.159330 206.366379 181.031937 257.161530 177.532318 106.258919 151.547348 350.701263
			</dihe0>
		</run>
		<run id="16">
			<free_NRG_binding>   -7.86</free_NRG_binding>
			<final_intermol_NRG> -10.24</final_intermol_NRG>
			<internal_ligand_NRG>-1.63</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>19.450607 15.820405 9.784910</tran0>
			<axisangle0>-0.69008775 0.71559161 -0.10820144 217.660614</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>37.685043 204.290848 181.027161 254.289749 177.123169 212.540573 342.560822 60.913258
			</dihe0>
		</run>
		<run id="9">
			<free_NRG_binding>   -7.81</free_NRG_binding>
			<final_intermol_NRG> -10.20</final_intermol_NRG>
			<internal_ligand_NRG>-1.61</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.221123 15.715585 9.993311</tran0>
			<axisangle0>0.65748913 -0.74996518 0.07252778 131.637817</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>184.000366 204.875305 184.353027 286.146301 128.646561 168.390732 11.356843 97.896545
			</dihe0>
		</run>
		<run id="20">
			<free_NRG_binding>   -7.80</free_NRG_binding>
			<final_intermol_NRG> -10.19</final_intermol_NRG>
			<internal_ligand_NRG>-1.58</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.487656 15.839693 10.600262</tran0>
			<axisangle0>-0.65179685 0.75408442 -0.08073140 210.366531</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>219.576645 229.514999 189.615417 264.316956 161.095490 105.883568 138.573669 350.303375
			</dihe0>
		</run>
		<run id="3">
			<free_NRG_binding>   -7.66</free_NRG_binding>
			<final_intermol_NRG> -10.05</final_intermol_NRG>
			<internal_ligand_NRG>-1.68</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>18.884143 14.364929 12.470813</tran0>
			<axisangle0>-0.74536606 0.65755402 0.10978228 156.741516</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>203.083603 213.866394 177.885010 273.179871 235.765564 311.142975 113.491386 235.250092
			</dihe0>
		</run>
		<run id="14">
			<free_NRG_binding>   -7.49</free_NRG_binding>
			<final_intermol_NRG> -9.88</final_intermol_NRG>
			<internal_ligand_NRG>-1.68</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>21.676299 15.681942 9.989594</tran0>
			<axisangle0>-0.63778777 0.76619503 -0.07856171 225.829559</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>46.501106 231.080887 189.542328 269.555969 143.282318 178.611771 13.890181 67.953087
			</dihe0>
		</run>
		<run id="1">
			<free_NRG_binding>   -7.42</free_NRG_binding>
			<final_intermol_NRG> -9.81</final_intermol_NRG>
			<internal_ligand_NRG>-1.87</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>20.924928 15.446873 11.763000</tran0>
			<axisangle0>0.65496255 -0.75032704 0.08962915 178.992798</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>41.401146 228.088654 190.785629 256.077240 192.956100 302.587830 112.592804 279.184448
			</dihe0>
		</run>
		<run id="18">
			<free_NRG_binding>   -6.54</free_NRG_binding>
			<final_intermol_NRG> -8.93</final_intermol_NRG>
			<internal_ligand_NRG>-1.12</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>18.200007 10.403461 8.030363</tran0>
			<axisangle0>0.70114678 0.45039429 -0.55275507 273.814850</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>61.827873 126.509811 222.897568 180.184677 62.857716 3.877677 358.754150 240.768219
			</dihe0>
		</run>
		<run id="6">
			<free_NRG_binding>   -6.34</free_NRG_binding>
			<final_intermol_NRG> -8.73</final_intermol_NRG>
			<internal_ligand_NRG>-1.50</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>17.642475 10.737096 10.407054</tran0>
			<axisangle0>-0.98387769 -0.09140641 0.15371907 110.277252</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>168.239822 140.960205 208.721558 188.981583 15.284373 329.170441 16.357250 135.423813
			</dihe0>
		</run>
		<run id="7">
			<free_NRG_binding>   -6.33</free_NRG_binding>
			<final_intermol_NRG> -8.72</final_intermol_NRG>
			<internal_ligand_NRG>-1.19</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>16.902627 10.395177 9.146150</tran0>
			<axisangle0>-0.93916635 -0.19739743 0.28107086 96.170914</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>235.232651 10.847622 175.693451 184.402161 26.340117 290.922058 128.122894 120.152153
			</dihe0>
		</run>
		<run id="19">
			<free_NRG_binding>   -6.20</free_NRG_binding>
			<final_intermol_NRG> -8.58</final_intermol_NRG>
			<internal_ligand_NRG>-1.12</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>18.671534 14.062493 14.098051</tran0>
			<axisangle0>-0.40887929 -0.91229710 -0.02305933 287.547760</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>10.600327 340.796265 19.151209 95.277748 229.258865 254.927521 179.039978 221.290176
			</dihe0>
		</run>
		<run id="13">
			<free_NRG_binding>   -5.37</free_NRG_binding>
			<final_intermol_NRG> -7.75</final_intermol_NRG>
			<internal_ligand_NRG>-1.27</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>17.387662 10.975529 9.906079</tran0>
			<axisangle0>-0.19430875 -0.98094038 0.00027684 179.770828</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>15.035855 132.504639 222.520020 61.100426 345.600922 329.639008 225.646713 289.899750
			</dihe0>
		</run>
		<run id="11">
			<free_NRG_binding>   -5.35</free_NRG_binding>
			<final_intermol_NRG> -7.74</final_intermol_NRG>
			<internal_ligand_NRG>-2.26</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>20.481651 12.589953 11.517474</tran0>
			<axisangle0>-0.89493190 0.35120522 -0.27523042 165.758179</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>354.227081 180.895416 1.748853 211.525635 351.247406 331.094818 141.116211 234.461609
			</dihe0>
		</run>
		<run id="15">
			<free_NRG_binding>   -5.20</free_NRG_binding>
			<final_intermol_NRG> -7.58</final_intermol_NRG>
			<internal_ligand_NRG>-1.76</internal_ligand_NRG>
			<torsonial_free_NRG> 2.39</torsonial_free_NRG>
			<tran0>16.970531 10.584629 11.952149</tran0>
			<axisangle0>0.53275938 -0.00678121 -0.84623960 220.768539</axisangle0>
			<ndihe>8</ndihe>
			<dihe0>148.944977 352.716888 333.188660 244.809219 202.357590 215.885895 344.260315 3.570147
			</dihe0>
		</run>
	</runs>
	<result>
		<clustering_histogram>
			<cluster cluster_rank="1" lowest_binding_energy="-8.00" run="2" mean_binding_energy="-7.84" num_in_clus="12" />
			<cluster cluster_rank="2" lowest_binding_energy="-7.81" run="9" mean_binding_energy="-7.81" num_in_clus="1" />
			<cluster cluster_rank="3" lowest_binding_energy="-6.54" run="18" mean_binding_energy="-6.44" num_in_clus="2" />
			<cluster cluster_rank="4" lowest_binding_energy="-6.34" run="6" mean_binding_energy="-6.34" num_in_clus="1" />
			<cluster cluster_rank="5" lowest_binding_energy="-6.20" run="19" mean_binding_energy="-6.20" num_in_clus="1" />
			<cluster cluster_rank="6" lowest_binding_energy="-5.37" run="13" mean_binding_energy="-5.37" num_in_clus="1" />
			<cluster cluster_rank="7" lowest_binding_energy="-5.35" run="11" mean_binding_energy="-5.35" num_in_clus="1" />
			<cluster cluster_rank="8" lowest_binding_energy="-5.20" run="15" mean_binding_energy="-5.20" num_in_clus="1" />
		</clustering_histogram>
		<rmsd_table>
			<run rank="1" sub_rank="1" run="2" binding_energy="-8.00" cluster_rmsd="0.00" reference_rmsd="232.38" />
			<run rank="1" sub_rank="2" run="12" binding_energy="-8.00" cluster_rmsd="1.47" reference_rmsd="232.79" />
			<run rank="1" sub_rank="3" run="4" binding_energy="-7.99" cluster_rmsd="1.43" reference_rmsd="232.76" />
			<run rank="1" sub_rank="4" run="5" binding_energy="-7.99" cluster_rmsd="1.07" reference_rmsd="232.31" />
			<run rank="1" sub_rank="5" run="10" binding_energy="-7.97" cluster_rmsd="1.46" reference_rmsd="232.87" />
			<run rank="1" sub_rank="6" run="8" binding_energy="-7.96" cluster_rmsd="1.43" reference_rmsd="232.90" />
			<run rank="1" sub_rank="7" run="17" binding_energy="-7.92" cluster_rmsd="1.19" reference_rmsd="232.37" />
			<run rank="1" sub_rank="8" run="16" binding_energy="-7.86" cluster_rmsd="1.59" reference_rmsd="232.21" />
			<run rank="1" sub_rank="9" run="20" binding_energy="-7.80" cluster_rmsd="1.77" reference_rmsd="232.86" />
			<run rank="1" sub_rank="10" run="3" binding_energy="-7.66" cluster_rmsd="1.50" reference_rmsd="232.07" />
			<run rank="1" sub_rank="11" run="14" binding_energy="-7.49" cluster_rmsd="1.93" reference_rmsd="232.80" />
			<run rank="1" sub_rank="12" run="1" binding_energy="-7.42" cluster_rmsd="1.94" reference_rmsd="232.74" />
			<run rank="2" sub_rank="1" run="9" binding_energy="-7.81" cluster_rmsd="0.00" reference_rmsd="232.58" />
			<run rank="3" sub_rank="1" run="18" binding_energy="-6.54" cluster_rmsd="0.00" reference_rmsd="231.01" />
			<run rank="3" sub_rank="2" run="7" binding_energy="-6.33" cluster_rmsd="0.92" reference_rmsd="230.93" />
			<run rank="4" sub_rank="1" run="6" binding_energy="-6.34" cluster_rmsd="0.00" reference_rmsd="231.51" />
			<run rank="5" sub_rank="1" run="19" binding_energy="-6.20" cluster_rmsd="0.00" reference_rmsd="234.39" />
			<run rank="6" sub_rank="1" run="13" binding_energy="-5.37" cluster_rmsd="0.00" reference_rmsd="230.20" />
			<run rank="7" sub_rank="1" run="11" binding_energy="-5.35" cluster_rmsd="0.00" reference_rmsd="234.69" />
			<run rank="8" sub_rank="1" run="15" binding_energy="-5.20" cluster_rmsd="0.00" reference_rmsd="228.62" />
		</rmsd_table>
	</result>
</autodock_gpu>
---------------------------

**Comment by atillack** [comment]
@shouti-fredchang This is fortunately not a bug :-)

The "best energy" displayed in the AutoStop table is the scoring function as calculated on the GPU - which is the sum of final_intermol_NRG and internal_ligand_NRG.

P.S. It is possible for final_intermol_NRG + internal_ligand_NRG to differ minutely from the AutoStop table (on the order of 0.01 kcal/mol) due to both rounding as well implementation differences between CPU and GPU math (dlg and xml numbers are recalculated on CPU).

**Comment by shouti-fredchang** [comment]
Confirmed, thanks for the clarification.
