### ISSUE TITLE
Error while running check.py file

### ISSUE THREAD

**Issue by Datadriven1** [ccsb-scripps/AutoDock-GPU#181]
Trying to do molecular docking with GPU according to https://catalog.ngc.nvidia.com/orgs/hpc/containers/autodock. 
But found error while running check.py file

"Traceback (most recent call last):
  File "./check.py", line 84, in <module>
    meandiff = check_output(reference_energies)
  File "./check.py", line 66, in check_output
    return (err/cnt)
ZeroDivisionError: float division by zero"

**Comment by sisco0** [comment]
Could you kindky check if the data folder is empty? The error seems related to zero results being found during the Python program execution. The referred test cases must be downloaded from AD-GPU set of 42 and placed under the `data` folder.
Could you consider the recommendations mentioned above and provide feedback?

**Comment by Datadriven1** [comment]
Now it works fine. Thanks for your support.
