### ISSUE TITLE
How to choose different Docking Search Parameter Algorithms?

### ISSUE THREAD

**Issue by Leo-T-Zang** [ccsb-scripps/AutoDock-GPU#185]
Hi,
I want to set Docking Search parameters algorithm for my docking (i.e., Genetic Algorithm, Simulated Annealing, and Local Search Parameter) like AutoDock 4. But I could not find the exact option in the documentation. Could you please tell me how to set specific algorithm for each docking?
Thank you,

**Comment by atillack** [comment]
Hi @Leo-T-Zang, while AD-GPU uses AD4's scoring function it uses an improved local search algorithm (Adadelta) by default and even Solis-Wets (SW, which is what AD4 uses) in AD-GPU should be slightly improved.

That said, the options listed under `SEARCH` if you run autodock_gpu without parameters or with `--help` are likely what you are asking for. There you will find options to control the genetic algorithm and some parameters for the local search.

By default, AD-GPU uses Adadelta (AD) in conjunction with AutoStop and a heuristics (which is implemented for both AD and SW). If you would like to use a specific amount of evaluations per run you can disable both with `-H 0` and `-A 0`. You can choose a different local search with `--lsmet` with AD and SW being implemented in both Cuda and OpenCL. OpenCL additionally has two other local searches (`fire` and `sd` - steepest decent) while Cuda also contains Adam (`adam`) but neither of those have been extensively tested and I would not recommend them for production runs.

**Comment by diogomart** [comment]
Genetic algorithms and simulated annealing are global search methods. The only global search method available in Autodock-GPU is a Lamarckian Genetic Algorithm (LGA), which is a genetic algorithm enhanced with a local search method (e.g. adadelta).
