### ISSUE TITLE
Manually specifying the bounding box instead of generating the affinity maps for Autodock-GPU input

### ISSUE THREAD

**Issue by zichaow** [ccsb-scripps/AutoDock-GPU#188]
Hi ! I am pretty new to the field and am slowly learning... I have a question using autodock-GPU vs. autodock-vina. I have a target protein for which I known the bounding box center and dimension. 

When I run autodock-vina in my application, I am not using autogrid to populate the affinity map files; instead, I know the bounding box dimensions, so I use the vina forcefield with a configuration file in which I manually specify the bounding box dimensions (see screenshot below, which is the instruction that I have been following). 

I wonder if I can do the same thing for autodock-GPU, i.e., using an explicit bounding box dimension configuration instead of generating the affinity maps as input for autodock-GPU? Currently, it seems that audock-GPU only accepts the affinity map files as input... Is there a way to modify the map files so I can use my own, known bounding box dimensions with autodock-GPU in my application?

Thanks a lot in advance!

![Screen Shot 2022-05-06 at 10 25 37 AM](https://user-images.githubusercontent.com/8587554/167164638-19752e20-420d-4e2a-8ed3-ee153406a951.png)

**Comment by Yongrui-Wang** [comment]
Hello，
Did you find any way, I was wondering about that too

**Comment by diogomart** [comment]
AutoDock-GPU needs the affinity maps. The affinity maps define the bounding box. The configuration file for autogrid, which typically ends in `.gpf`, defines the bounding box with `gridcenter`, `npts`, and `spacing` keywords.

**Comment by Yongrui-Wang** [comment]
Thanks!
