### ISSUE TITLE
Add option equivalent to AutoDock epdb

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#19]
It is an option used in `*.dpf` files: it means running a single energy calculation.

For implementing this, there is the requirements:

* The ligand and the grids are needed
* The ligand is scored in the input orientation

See pages 44 and 59 in the [AutoDock User Guide](http://autodock.scripps.edu/faqs-help/manual/autodock-4-2-user-guide/AutoDock4.2_UserGuide.pdf).

The name of the option is _"epdb"_ but something like _"score_only"_ or _"single_point"_ would not violate the principle-of-least-astonishment.

**Comment by L30nardoSV** [comment]
@diogo.martins: while checking the RMSD issue #20, 

I've casually discovered that an option equivalent to **epdb** seems to be already implemented in OCLADock as the `-rlige` command-line, which stands for _reference-ligand energy_ (the randomized one):

Reference below were taken from latest master branch (commit ebf9a4b0f0bb4b30cb95455b465dc2594230cae7):

1. Flag definition in [/host/src/getparameters.cpp](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/getparameters.cpp)

* [Default value](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/getparameters.cpp#L162)
* [Using command-line flag to set parameter](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/getparameters.cpp#L442)

2. Conditional function call in [/host/src/main.cpp](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/main.cpp#L101)

_Perhaps we could have used this for printing energies from initial **2brt** during our gradient debugging?_ :neutral_face:

3. Implementation in [/host/src/processligand.cpp](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/processligand.cpp), within [`void print_ref_lig_energies_f()`](https://github.com/ccsb-scripps/AutoDock-GPU/blob/ebf9a4b0f0bb4b30cb95455b465dc2594230cae7/host/src/processligand.cpp#L1108)

Any comments on this? Probably you can easily confirm this is true?

**Comment by L30nardoSV** [comment]
It  works :smile:

**Comment by kbaitsi** [comment]
Ι am using Autodock 4.2.6 and I came across the epdb option. Ι ran a lot of dpf files (following instructions on the user guide) but I keep getting Unbound System's energy (4)= 0.00 which doesn't seem correct. I know my comment is a bit of topic but any thoughts on what I might be doing wrong or how to fix this? Thanks in advance.

**Comment by diogomart** [comment]
Hi. In autodock 4.2 the unbound energy is set to the value of the intramolecular energy. Is the intramolecular energy also zero?

**Comment by kbaitsi** [comment]
No, for example I get this
![image](https://user-images.githubusercontent.com/92086449/139881310-69c8772d-aaf9-4819-baec-4d8532b94120.png)

**Comment by diogomart** [comment]
I don't know why it is setting the unbound energy to zero. I expected unbound (4) to be the same as internal energy (2), which is the default in regular dockings (not epdb).

**Comment by kbaitsi** [comment]
Yes, in the regular dockings I perform 4 is equal to 2.
I guess some parameter is set in the wrong way when It comes to epdb. Thank you so much for your response though.
