### ISSUE TITLE
Unknown atom type

### ISSUE THREAD

**Issue by Teohoho** [ccsb-scripps/AutoDock-GPU#190]
Hello! I attempted to run a docking simulation using AutoDock-GPU, v1.5.3-24 and I get the following error:

`Error: Ligand includes atom with unknown type: Pt.`

I have used a parameter file to explicitly define the parameters for Pt, Se and B, and added the corresponding line into my .gpf file prior to generating the map files and I successfully generated them. However, when running the actual docking simulation, it stops and returns the above error, along another one that reads:

`Error: Could not identify ligand atom type Se.`

My ligand set includes molecules with these metals, alongside Boron, which works, despite not being in the default parameter set.
Thank you.

**Comment by diogomart** [comment]
Hello,

AutoDock-GPU does not read the parameter file. Boron has been included recently. It may be reasonable to replace Selenium with Sulfur, and it is possible to do this with `-T Se=S`, which will treat `Se` as `S` for direct interactions: ligand-ligand, and ligand-flexres.

**Comment by Teohoho** [comment]
Thank you for the quick reply! So there is currently no way to manually add parameters for other elements, such as Platinum?

**Comment by diogomart** [comment]
Hi, sorry, forgot to reply. Unfortunately there isn't.
