### ISSUE TITLE
cannot perform contact_analysis 

### ISSUE THREAD

**Issue by alfredoq** [ccsb-scripps/AutoDock-GPU#193]
Good morning,
I am trying to use the 'contact_analysis' option however I cannot find out how the job is invoked. I have already docked my ligand, thus the corresponding .xml and .dlg files are in the directory. I run the following command:

_autodock_gpu_128wi --xml2dlg ligand.xml --contact_analysis 1 --dlg2stdout 1_

but I get the following error: 

_AutoDock-GPU version: v1.5-release_

_Analyzing 1 xml file (contact analysis cutoffs: R=2.1 Å, H=3.7 Å, V=4.0 Å)_

_Error: No ligand or flex res file specified._

_Error in init_liganddata, stopped job._

_Error in setup of Job #1:_
_(   Grid map file: receptor.maps.fld )_
_(   Ligand file: ligand.pdbqt )_
_Run time of entire job set (1 file): 0.080 sec_
_Processing time: 0.000 sec_

_Warning: The following jobs were not successful:_
         _Job 0: ligand.pdbqt_

In addition, if i specify explicitly the corresponding ligand the same error is obtained. Also, if he 'contact_analysis' option is passed along with the docking command, no result is obtained,

Any hint on how to perform the contact analysis is greatly appreciated,

Thanks in advance for the support,

kind regards

Alfredo

**Comment by atillack** [comment]
@alfredoq Thank you reporting this. This is a bug that snuck in with the simple covalent code after the 1.5.3 release (https://github.com/ccsb-scripps/AutoDock-GPU/releases/tag/v1.5.3).

A fix is in preparation and I'll PR it soon.

**Comment by alfredoq** [comment]
thank you @atillack for the update. Great news a fix is in preparation,
kind regards
Alfredo

**Comment by alfredoq** [comment]
@atillack , good morning, has this issue having to do with contact analysis been solved in the current code?

kind regards

Alfredo

**Comment by atillack** [comment]
@alfredoq Yes, the current develop branch contains the fix (see PR #195 above).

**Comment by alfredoq** [comment]
Thank you for the reply @atillack
