### ISSUE TITLE
-gbest option not extracting the lowest energy docked pose

### ISSUE THREAD

**Issue by alfredoq** [ccsb-scripps/AutoDock-GPU#194]
**Describe the bug**
issue: upon applying the --gbest option, the  .pdbqt file extracted does not corresponds to the lowest energy docked pose indicated in the .dlg file (i.e. lowest energy pose in cluster 1).

**Comment by atillack** [comment]
@alfredoq The `--gbest` option outputs the lowest scoring function energy pose (which is inter + intramolecular energy). This is different from the lowest binding energy used for clustering which with AD4's `bound == unbound` default setting does not contain the intramolecular energy.

**Comment by alfredoq** [comment]
Thank you very much @atillack for this comment,
kind regards,

Alfredo
