### ISSUE TITLE
Is docking with two receptors at the same time feasible?

### ISSUE THREAD

**Issue by Glinttsd** [ccsb-scripps/AutoDock-GPU#196]
Hi,
I wonder if docking with one ligand to two receptors at the same time feasible for autodock-gpu? if not, are there any other solutions?

**Comment by diogomart** [comment]
Hi,

No, that's not possible.

If the two receptors exist as a molecular assembly, it would make sense to concatenate them into a single receptor.

**Comment by Glinttsd** [comment]
Many thanks! One last question, how about one receptor to two ligands?

**Comment by diogomart** [comment]
Autodock-gpu can only dock one ligand at a time. The `--filelist` argument is useful for docking multiple ligands, one at a time, in a single command line call.

Autodock-vina can dock multiple ligands simultaneously.

**Comment by Glinttsd** [comment]
Many thanks!
