### ISSUE TITLE
Flexible Residue Positions when Ligand is Docked

### ISSUE THREAD

**Issue by stikeleather** [ccsb-scripps/AutoDock-GPU#197]
When performing flexible docking, and with --gbest enabled, is there a way to output the positions of the flexible residues as they are found with the Ligand docked?

Does the --npdb flag output the top # hits? As in, --npdb 5 would output the top 5 best poses? Again, would there be a way to output the positions of flexible residues for each pose? 

Thanks for any help

**Comment by atillack** [comment]
@Professor333 "Best", similarly to `--gbest`, in the context of `--npdb` refers to the scoring function value, not the estimated free binding energy (which is what the dlg output data tables and clustering analysis is sorted by).

`--npdb 5` would output the 5 top scoring poses for each run.

Currently, its output does not contain the flexible residue atoms but it's a feature I can add in a future PR.

**Comment by stikeleather** [comment]
Thank you for adding this feature. Much appreciated.
