### ISSUE TITLE
AutoDockGPU sometimes outputs very high positive numbers when screening libraries of ligands.

### ISSUE THREAD

**Issue by SamuelOjeda** [ccsb-scripps/AutoDock-GPU#200]
This is an issue I ran into while trying to screen libraries of ligands. Some ligand docking finish docking ridiculously fast (< .05 seconds) and output massive positive numbers (as shown in the screenshot below). Does anyone know if this is a known issue from Autodock4's scoring function or if it's more likely to be an input file generation mistake on my end? 

AutodockGPU terminal output:

AutoDock-GPU version: 

Running 1 docking calculation

Cuda device:                              NVIDIA GeForce RTX 3080 (#1 / 4)
Available memory on device:               9429 MB (total: 10010 MB)

CUDA Setup time 0.109615s

Running Job #1
    Using heuristics: (capped) number of evaluations set to 1132076
    Local-search chosen method is: ADADELTA (ad)

Rest of Setup time 0.005732s

Executing docking runs, stopping automatically after either reaching 0.15 kcal/mol standard deviation of
the best molecules of the last 4 * 5 generations, 42000 generations, or 1132076 evaluations:

Generations |  Evaluations |     Threshold    |  Average energy of best 10%  | Samples |    Best energy
------------+--------------+------------------+------------------------------+---------+-------------------
          0 |          150 |16777216.00 kcal/mol |    0.00 +/-    0.00 kcal/mol |       0 |16777216.00 kcal/mol
          5 |        25999 |16777216.00 kcal/mol |    0.00 +/-    0.00 kcal/mol |       0 |16777216.00 kcal/mol
         10 |        50075 |16777216.00 kcal/mol |    0.00 +/-    0.00 kcal/mol |       0 |16777216.00 kcal/mol
         15 |        73887 |16777216.00 kcal/mol |    0.00 +/-    0.00 kcal/mol |       0 |16777216.00 kcal/mol
         20 |        97534 |16777216.00 kcal/mol |    0.00 +/-    0.00 kcal/mol |       0 |16777216.00 kcal/mol
------------+--------------+------------------+------------------------------+---------+-------------------

                                   Finished evaluation after reaching
                                    0.00 +/-    0.00 kcal/mol combined.
                                 0 samples, best energy 16777216.00 kcal/mol.

Docking time 0.028322s

Shutdown time 0.000185s

Job #1 took 0.034 sec after waiting 0.179 sec for setup

Run time of entire job set (1 file): 0.235 sec
Processing time: 0.021 sec

All jobs ran without errors.

Ligand pdbqt file: 

REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ATOM      1  C   UNL     1       1.381  -0.213   0.014  0.00  0.00    -0.062 A 
ATOM      2  C   UNL     1       0.865   1.082   0.004  0.00  0.00    -0.061 A 
ATOM      3  C   UNL     1      -0.518   1.285   0.032  0.00  0.00    -0.055 A 
ATOM      4  C   UNL     1      -1.400   0.194  -0.012  0.00  0.00    -0.010 A 
ATOM      5  C   UNL     1      -0.863  -1.102  -0.008  0.00  0.00    -0.055 A 
ATOM      6  C   UNL     1       0.517  -1.304   0.017  0.00  0.00    -0.061 A 
ATOM      7  C   UNL     1      -2.891   0.437  -0.147  0.00  0.00    +0.115 C 
ATOM      8  O   UNL     1      -3.613  -0.802  -0.116  0.00  0.00    -0.487 OA
ATOM      9  C   UNL     1      -4.940  -0.757  -0.430  0.00  0.00    +0.121 A 
ATOM     10  C   UNL     1      -5.769  -1.691   0.196  0.00  0.00    -0.018 A 
ATOM     11  C   UNL     1      -7.144  -1.781  -0.132  0.00  0.00    -0.037 A 
ATOM     12  C   UNL     1      -7.720  -0.892  -1.057  0.00  0.00    +0.034 A 
ATOM     13  C   UNL     1      -6.853  -0.001  -1.694  0.00  0.00    -0.037 A 
ATOM     14  C   UNL     1      -5.488   0.072  -1.393  0.00  0.00    -0.018 A 
ATOM     15  N   UNL     1      -9.131  -0.880  -1.317  0.00  0.00    -0.278 N 
ATOM     16  C   UNL     1      -9.801   0.035  -2.162  0.00  0.00    +0.305 C 
ATOM     17  O   UNL     1      -9.296   0.934  -2.826  0.00  0.00    -0.265 OA
ATOM     18  C   UNL     1     -11.352  -0.101  -2.267  0.00  0.00    +0.318 C 
ATOM     19  O   UNL     1     -11.913  -0.922  -1.591  0.00  0.00    -0.263 OA
ATOM     20  N   UNL     1     -11.925   0.817  -3.204  0.00  0.00    -0.199 N 
ATOM     21  N   UNL     1     -13.295   0.850  -3.407  0.00  0.00    -0.187 NA
ATOM     22  C   UNL     1     -13.859   1.727  -4.201  0.00  0.00    +0.054 C 
ATOM     23  C   UNL     1     -15.381   1.827  -4.250  0.00  0.00    +0.012 A 
ATOM     24  C   UNL     1     -16.196   2.126  -5.391  0.00  0.00    -0.006 A 
ATOM     25  C   UNL     1     -17.600   1.857  -5.319  0.00  0.00    +0.167 A 
ATOM     26  C   UNL     1     -18.025   0.998  -4.355  0.00  0.00    +0.167 A 
ATOM     27  C   UNL     1     -17.417   1.220  -3.139  0.00  0.00    -0.002 A 
ATOM     28  C   UNL     1     -16.075   1.558  -3.072  0.00  0.00    +0.030 A 
ATOM     29 BR   UNL     1     -15.367   1.539  -1.315  0.00  0.00    -0.050 Br
ATOM     30  O   UNL     1     -19.381   0.779  -4.406  0.00  0.00    -0.453 OA
ATOM     31  C   UNL     1     -19.707   2.157  -4.449  0.00  0.00    +0.233 C 
ATOM     32  O   UNL     1     -18.681   2.838  -5.294  0.00  0.00    -0.453 OA
ATOM     33  H   UNL     1       2.455  -0.373   0.023  0.00  0.00    +0.062 HD
ATOM     34  H   UNL     1       1.541   1.932  -0.036  0.00  0.00    +0.062 HD
ATOM     35  H   UNL     1      -0.900   2.303   0.074  0.00  0.00    +0.062 HD
ATOM     36  H   UNL     1      -1.517  -1.970  -0.031  0.00  0.00    +0.062 HD
ATOM     37  H   UNL     1       0.912  -2.316   0.021  0.00  0.00    +0.062 HD
ATOM     38  H   UNL     1      -3.030   0.972  -1.094  0.00  0.00    +0.075 HD
ATOM     39  H   UNL     1      -3.238   1.060   0.685  0.00  0.00    +0.075 HD
ATOM     40  H   UNL     1      -5.338  -2.345   0.954  0.00  0.00    +0.065 HD
ATOM     41  H   UNL     1      -7.724  -2.564   0.353  0.00  0.00    +0.064 HD
ATOM     42  H   UNL     1      -7.197   0.671  -2.469  0.00  0.00    +0.064 HD
ATOM     43  H   UNL     1      -4.893   0.778  -1.959  0.00  0.00    +0.065 HD
ATOM     44  H   UNL     1      -9.713  -1.538  -0.803  0.00  0.00    +0.155 HD
ATOM     45  H   UNL     1     -11.319   1.508  -3.636  0.00  0.00    +0.178 HD
ATOM     46  H   UNL     1     -13.272   2.426  -4.821  0.00  0.00    +0.085 HD
ATOM     47  H   UNL     1     -15.717   2.139  -6.378  0.00  0.00    +0.066 HD
ATOM     48  H   UNL     1     -18.036   1.308  -2.252  0.00  0.00    +0.067 HD
ATOM     49  H   UNL     1     -19.679   2.484  -3.389  0.00  0.00    +0.117 HD
ATOM     50  H   UNL     1     -20.755   2.304  -4.746  0.00  0.00    +0.117 HD
TER 

Im using standard settings for all the calculations, but here is my autodockGPU command if that helps:
autodock_gpu_64wi --ffile $protein --lfile $lig --devnum 1 -N $output -x 0

Any help/advice would be greatly appreciated!

**Comment by diogomart** [comment]
I could reproduce this behavior using a random ligand and a tiny search space (the search space is defined by the precalculated energy grid maps). It seems that the stopping criterion is met rapidly when the ligand does not fit the grid maps. So, a huge energy and aborting as fast as possible are both desirable and correct.

For your ligand in particular, the heterocycle with the Br is distorted, and it could use rotatable bonds. Maybe it would fit the grid maps if the rotatable bonds were rotatable during docking. At the moment, we recommend preparing ligands with [meeko](https://github.com/forlilab/Meeko) from SDF files with 3D coordinates and hydrogens.

It is also possible that you need larger grid maps, or that the grid maps are reasonable but this ligand is too big for the receptor.

**Comment by SamuelOjeda** [comment]
Thank you for the quick response!
Increasing my grid size-resolved the issue. <1% of ligands report positive binding affinities under my new parameters.

About the ligand .pdbqt file generation:
I am creating my files starting from smiles and using the oddt package to generate 3D coordinates and calculate partial charges. Would you recommend I use open-babel to generate .SDF files from smiles and then use those as my input files for meeko?

**Comment by diogomart** [comment]
I don't have experience with oddt, but using RDKit's ETKDG + UFF minimization seems to produce reasonably good geometries. See the original post in [this issue](https://github.com/forlilab/Meeko/issues/8) for an example.

**Comment by SamuelOjeda** [comment]
I see. I didn't even realize that my old method wasn't generating Torsion trees properly.
I remade all of my decoys .pdbqt input directories utilizing meeko (copying the code you linked) and can confirm a drastic improvement in docking/BA ranking accuracy.
Using the ROC calculation posted on the original DUD-e paper, ROCauc values jumped from .58 -> .81. 
Thanks for the advice!

**Comment by diogomart** [comment]
That's good to hear :)
