### ISSUE TITLE
"Could not identify ligand atom type Ni"

### ISSUE THREAD

**Issue by pattabik83** [ccsb-scripps/AutoDock-GPU#202]
Hi!

I am trying to do a docking with CNT molecule which contains Ni, Mg and O atoms.
I am able to do the docking with autodock4 in windows and linux by adding the parameter file in gpf and dpf files.

But in autodock-gpu, I am unable to run the same system. This is the command I gave 

`autodock_gpu_64wi --ffile protein.maps.fld --lfile ligand.pdbqt --derivtype Ni --nrun 100`

Thanks.

**Comment by diogomart** [comment]
Hi,

Autodock-gpu can't read the parameter file, but it can pretend that Ni is, for example, Mg, with `--derivtype Ni=Mg`.

Related to #190

**Comment by pattabik83** [comment]
Thanks for the prompt response.
Great! it worked.
Thanks for the gpu-tool.
