### ISSUE TITLE
Maximum number of atoms is 256

### ISSUE THREAD

**Issue by cjl232** [ccsb-scripps/AutoDock-GPU#205]
Hi,
I am trying to run a docking job with a protein and peptide (~50 AA long) and I receive an error for the maximum number of atoms is 256. Is there any way I can get around this or increase this amount in a constants file? 

I was previously able to run the job on vina (took 6 days) and wanted to trial the GPU AutoDock to see if I could greatly increase the throughput. 

Many thanks in advance!

**Comment by diogomart** [comment]
Hi,

It's here: https://github.com/ccsb-scripps/AutoDock-GPU/blob/2ecd342b493d1e9b7b488ea2b642df1e0adcb50d/common/defines.h#L83

50 amino acids is too big for autodock. It's difficult to converge when the number of rotatable bonds is greater than 20. Furthermore, bond lengths and angles are rigid, and that may be a harsh approximation to a such a large molecule, as small changes at the center would have a large impact at the ends.

At 50 amino acids, the peptide is eligible for protein status, and you could try tools for folding prediction and protein-protein docking. Another idea that comes to mind is to break the peptide is smaller chunks and dock each chunk individually.
