### ISSUE TITLE
Standard output

### ISSUE THREAD

**Issue by pnakliang** [ccsb-scripps/AutoDock-GPU#218]
I have a general question regarding the output files. can I convert the dlg file to an AutoDock vina output file format?

**Comment by diogomart** [comment]
What is the end goal? The SDF format is better for software interoperability, see `mk_export.py` from [Meeko](https://github.com/forlilab/Meeko).

**Comment by pnakliang** [comment]
> What is the end goal? The SDF format is better for software interoperability, see `mk_export.py` from [Meeko](https://github.com/forlilab/Meeko).

I have tried that, but it doesn't work well because I did prepare the ligand using `mk_ligand_prepare.py` from  [Meeko](https://github.com/forlilab/Meeko)

**Comment by diogomart** [comment]
The DLG is a PDBQT with extra info, the following _**may**_ be good enough, depending on what the use is:
```sh
grep ^DOCKED results.dlg | cut -c 9- > docked.pdbqt
```

**Comment by pnakliang** [comment]
Thank you, it's very helpful

**Comment by tubiana** [comment]
I just post the command with openbabel as well just in case some people want it...

`obabel -ipdbqt results.dlg -opdbqt -O docked.pdbqt -ad`

NOTE: the `-ad` precise the `d` argument for the `pdbqt` READING format. (check https://openbabel.org/docs/current/FileFormats/AutoDock_PDQBT_format.html#read-options and https://openbabel.org/docs/current/FileFormats/Overview.html for how to give input/output arguments).
