### ISSUE TITLE
Multiple ligands docking to one receptor

### ISSUE THREAD

**Issue by pnakliang** [ccsb-scripps/AutoDock-GPU#219]
Can we perform multiple ligands (e.g. 2 ligands) docking to one receptor at the same time using AutoDock GPU? I remember that we could perform this kind of docking using AutoDock Vina. If yes how to prepare the input files and run?

**Comment by tubiana** [comment]
Someone corect me if I'm wrong but this is how I dot it.

The filelist fomat should be like this:
```
receptor_prepared.maps.fld
./molecules/TCMDC-140876.pdbqt
TCMDC-140876
./molecules/TCMDC-124866.pdbqt
TCMDC-124866
```

So 
First line = FLD file
2nd Line = path to ligand1
3rd line = NAME of ligand 1
4th Line = path to ligand 2
5th line = NAME of ligand 2.

I generate it with a python code : 
```python
import os
import glob
from pathlib import Path

os.chdir("/home/thibault/work/projects/other/Sylvie/new_test")
molecules = glob.glob("molecules/*.pdbqt")
with open("molecules_list.list","w") as output:
    output.write("WRITE_YOUR_FLD_FILE_HERE\n")
    for mol in molecules:
        name = Path(mol).stem
        output.write(f"./{mol}\n")
        output.write(f"{name}\n")
```

**Comment by pnakliang** [comment]
I have tried as you suggested. but it turned out to be a single ligand at the time. any other suggestions?

**Comment by diogomart** [comment]
No, AD-GPU does not dock multiple ligands simultaneously, only one at a time.
