### ISSUE TITLE
covalent docking free energy estimate

### ISSUE THREAD

**Issue by agoliaei** [ccsb-scripps/AutoDock-GPU#226]
Hi,
I think I managed to figure out how to run covalent docking using both Meeko and AD-GPU. I am wondering, is it expected to see a large positive number as the estimated free energy, or am I making a mistake the way I set up my simulation? I guess I am confused on the energy terms that are used for "Final Total Internal Energy". 

DOCKED: USER    Estimated Free Energy of Binding    = +66.49 kcal/mol  [=(1)+(2)+(3)-(4)]
DOCKED: USER
DOCKED: USER    (1) Final Intermolecular Energy     =  +0.00 kcal/mol
DOCKED: USER        vdW + Hbond + desolv Energy     =  +0.00 kcal/mol
DOCKED: USER        Electrostatic Energy            =  +0.00 kcal/mol
DOCKED: USER        Moving Ligand-Fixed Receptor    =  +0.00 kcal/mol
DOCKED: USER        Moving Ligand-Moving Receptor   =  +0.00 kcal/mol
DOCKED: USER    (2) Final Total Internal Energy     = +66.49 kcal/mol
DOCKED: USER    (3) Torsional Free Energy           =  +0.00 kcal/mol
DOCKED: USER    (4) Unbound System's Energy         =  +0.00 kcal/mol

**Comment by diogomart** [comment]
Hi, can you share your input files and the AD-GPU command you used?

**Comment by agoliaei** [comment]
Thanks so much for replying. Please find here a sample. I don't know what I am doing wrong. In this one it give +80 kcal/mol as estimate.
I appreciate your help.

![image](https://user-images.githubusercontent.com/38381148/233670316-ca74499e-38c7-4346-a6c5-0dc73258ec45.png)
[sample_cov_dock.zip](https://github.com/ccsb-scripps/AutoDock-GPU/files/11296956/sample_cov_dock.zip)

**Comment by agoliaei** [comment]
Upon further exploring, looks like AD4 handles covalent binding in a different way than AD-GPU. The estimated free energy looks more realistic, however, it takes forever to finish calculations on CPU. 
I have a question, looks like in covalent binding all the "inter" molecular terms are set to zero. Does this mean docking a ligand that is bound covalently is not taking vdW, Hbond, Elect,... energies between the ligand and the rest of the protein into account? How can this result in finding a reliable pose (redocking experiments)? Am I understanding this correctly?

![Screenshot from 2023-04-23 10-06-51](https://user-images.githubusercontent.com/38381148/233844819-7699560b-9bb1-4e89-a2cf-b959cc719db7.png)

**Comment by agoliaei** [comment]
Closing as I found the problem. My set up was incorrect.
Thank you!
