### ISSUE TITLE
 autogrid4: FATAL ERROR: Sorry, I can't find or open AD4_parameters.dat

### ISSUE THREAD

**Issue by amir-tagh** [ccsb-scripps/AutoDock-GPU#231]
Hello,

there is a Br atom in my ligand and I have copied the AD4_parameters.dat in the dir with autodock4 & autogrid4 exe and added the parameters to the .gpf file as following, but I am getting the error message:'

can you please let me know if I am doing it right to handle the heavy atoms.

Thanks,
Amir

error
--------------------------------------
autogrid4: FATAL ERROR: Sorry, I can't find or open AD4_parameters.dat

.gpf file
----------------------------------------------------------------------------------
parameter_file AD4_parameters.dat    # AD4 for heavy atoms
npts 100 100 100                     # num.grid points in xyz
gridfld protein.maps.fld             # grid_data_file
spacing 0.375                        # spacing(A)
receptor_types A C HD N OA SA        # receptor atom types
ligand_types B C HD N NA OA          # ligand atom types
receptor protein.pdbqt               # macromolecule
gridcenter auto                      # xyz-coordinates or auto
smooth 0.5                           # store minimum energy w/in rad(A)
map protein.B.map                    # atom-specific affinity map
map protein.C.map                    # atom-specific affinity map
map protein.HD.map                   # atom-specific affinity map
map protein.N.map                    # atom-specific affinity map
map protein.NA.map                   # atom-specific affinity map
map protein.OA.map                   # atom-specific affinity map
elecmap protein.e.map                # electrostatic potential map
dsolvmap protein.d.map              # desolvation potential map
dielectric -0.1465                   # <0, AD4 distance-dep.diel;>0, constant

**Comment by diogomart** [comment]
Hi, I think the path is relative to the current working directory, so you need to place the .dat file in the directory that autogrid is run from. Alternatively, it should be possible to specify the full path to the .dat file.

**Comment by amir-tagh** [comment]
Hi, 

So, I changed the Br in the .dat file to B and autogrid worked. Now autodock_gpu_64wi is complaining about " atom with unknown type: A or B!".
Is there a way around this?

Thanks,

error
------------------------------------------------------------------------
CUDA Setup time 0.095693s
Error: Ligand includes atom with unknown type: A or B!

**Comment by diogomart** [comment]
Which version (with commit ID) are you using? e.g.
```console
$ ./autodock_gpu_128wi 
AutoDock-GPU version: v1.5.3-48-gf9ea8ba79f3cf73a7873357f949a0043c524ca2b
```

**Comment by amir-tagh** [comment]
it is:
autodock_gpu_64wi --version
AutoDock-GPU version: v1.4-release

**Comment by diogomart** [comment]
Updating should fix it.

**Comment by amir-tagh** [comment]
Can you please let me know how I can update the current version.

can not find any documents googling it.

https://catalog.ngc.nvidia.com/orgs/hpc/containers/autodock

**Comment by amir-tagh** [comment]
I made a new installation on HPC and it is working.  Thanks!
