### ISSUE TITLE
Maximum number of --nruns

### ISSUE THREAD

**Issue by Mishakolok** [ccsb-scripps/AutoDock-GPU#232]
Hello,
It seems like the maximum available number of nruns is limited to 1000. Is there a particular reason behind this? I think that with modern GPUs increasing this number shouldn't seriously impact performance (for example, on my RTX 4070 a docking simulation with 1000 runs and 90 x 90 x 90 A takes only several seconds.

**Comment by diogomart** [comment]
I'm curious, for your system, using the default number of runs:
1. do you get comparable results to 1000 runs
2. how much faster is it than with 1000 runs

**Comment by Mishakolok** [comment]
My system consists of Human Serum Albumin as a receptor (PDB 1N5U) and a Porhyrin derivative as a ligand (for example TmPyP4 https://atb.uq.edu.au/molecule.py?molid=1271234). My goal was to try to identify potential binding sites via blind docking, so that they could be verified with our experimental data.
The time of the run with default settings (nrun=20):
```
Job #1 took 1.797 sec after waiting 2.507 sec for setup

(Thread 3 is processing Job #1)
Run time of entire job set (1 file): 4.381 sec
Processing time: 0.076 sec

All jobs ran without errors.
```
And with nruns=1000
```
Job #1 took 2.751 sec after waiting 2.522 sec for setup

(Thread 9 is processing Job #1)
Run time of entire job set (1 file): 9.408 sec
Processing time: 4.131 sec

All jobs ran without errors.
```

All the other settings were set to default (except --npdb set to 1).
The best conformations look quite similar (green for 20 runs and red for 1000 runs). However, the energy of best poses for 20 runs is not stable, varying between -5.3 and -5.7 kcal/mol between runs launched with the same command. The same applies to 1000 runs scenario. 
![image](https://github.com/ccsb-scripps/AutoDock-GPU/assets/17143500/5a0e1bfd-d125-4e9e-9094-93fe57737958)
Increasing the number of populations to 2048 (maximum) doesn't really improve variablity for 20 runs, while the situation for 1000 runs becomes more stable (between -5.6 and -5.7 kcal/mol). I tested this by running both cases about 5 times, so this might be wrong.
With the population of 2048 timings for 20 runs look like this:

```
Job #1 took 1.728 sec after waiting 2.511 sec for setup

(Thread 5 is processing Job #1)
Run time of entire job set (1 file): 5.591 sec
Processing time: 1.351 sec
```

And for 1000 runs
```
Job #1 took 23.167 sec after waiting 2.498 sec for setup

(Thread 1 is processing Job #1)
Run time of entire job set (1 file): 93.131 sec
Processing time: 67.428 sec
```
Obviously, it's significantly longer the the default case, but for single dockings might be passable.

I hope this information will be of use to you. I am a bit new to the docking field, so I might have missed some important aspects of it.

**Comment by diogomart** [comment]
Interesting! Thanks for sharing :+1: 

@atillack seems like a good case for allowing larger `nrun`. What do you think?

**Comment by atillack** [comment]
@Mishakolok @diogomart We can probably increase that number a little bit. There's one little wrinkle in the Cuda code allocating memory based on the maximum number of runs I want to take care of first - I'll PR when ready :-)

**Comment by atillack** [comment]
@Mishakolok @diogomart PR #233 is up.
