### ISSUE TITLE
Different Default Save Path for dlg Files when Using RTX4090

### ISSUE THREAD

**Issue by NiBoyang** [ccsb-scripps/AutoDock-GPU#235]
I have noticed a peculiar behavior in the saving of the docking results' dlg files when using the RTX4090 GPU card, as compared to when using the 30 series cards.

While running the AutoDock-GPU on the 30 series cards, the default save path for the dlg files is in the current directory where the program is run. However, when using the RTX4090 card, I've observed that the default save path changes to the directory where the **maps.fld** files is located.

This inconsistency between the behavior of different graphics cards is not expected and adds confusion when managing output files.

Could you please check if this is a bug, or if there is a specific reason for this difference? Your feedback and support are much appreciated.

**Comment by diogomart** [comment]
What is the commit ID of the version you are using? This information is in the first line printed to stdout. This behavior was changed recently, perhaps there are different versions aliased depending on which GPU is available.

**Comment by diogomart** [comment]
See pull request #225

**Comment by NiBoyang** [comment]
The version that saves the dlg files to the current working directory is: v1.5.3-48-gf9ea8ba79f3cf73a7873357f949a0043c524ca2b

The version that saves the dlg files to the directory where the maps.fld files is located is: v1.5.3-53-gf58a5173fa2f4c82a74b40bc895ad7e65de59f47

The batch file input is formatted like (for both versions above):

'''
/home/s2263780/litpcba/tp53/lig/4agq_ligand.maps.fld
/home/s2263780/litpcba/tp53/lib/144205114/144205114.pdbqt
144205114
/home/s2263780/litpcba/tp53/lib/144213700/144213700.pdbqt
144213700
/home/s2263780/litpcba/tp53/lib/144211437/144211437.pdbqt
144211437
...
'''

Is that the different version caused the issue? What should I do If I still want the dlg files to be saved to the current working directory using the latest version.

**Comment by diogomart** [comment]
In the latest version, the path of output files is relative to the path to the filelist, instead of being relative to working directory where autodock-gpu is executed. You can also specify an absolute path for output filenames or even just move the filelist file to the desired output directory.
