### ISSUE TITLE
Zero Affinities with GPU but not in Vina

### ISSUE THREAD

**Issue by syedzayyan** [ccsb-scripps/AutoDock-GPU#238]
Hello!

I am trying to dock some ligands in a batch onto the Adenosine Receptor. I have attached the code I am using. I keep getting zero affinity even though on Vina or Webina I do not with the duplicate PDBQT files.

I found out that it could be because that Autodock is not able to find a satisfactory binding pose but how is that even possible if Vina and Webina are able to generate poses in the 4-7 ranges?

I used the same bounding box when running Webina and Vina.

[ad-gpu-adenosine-receptors.ipynb.zip](https://github.com/ccsb-scripps/AutoDock-GPU/files/12368125/ad-gpu-adenosine-receptors.ipynb.zip)

Thank You! :)

**Comment by diogomart** [comment]
Hi,

It may be because in the GPF for autogrid, the search space (grid box) is defined by number of grid points, which are 0.375 Angstroms apart, so you need to divide the size by spacing. Do not increase spacing as that will be too coarse.

**Comment by syedzayyan** [comment]
It was that! thanks!
