### ISSUE TITLE
AutoDock-GPU Virtual Screening

### ISSUE THREAD

**Issue by apaydinemre** [ccsb-scripps/AutoDock-GPU#243]
Is it possible to do virtual screening using AutoDock-GPU? If possible, how is it done, is there a manual for this? I would be very grateful if you can help me with this. Thank you!

**Comment by diogomart** [comment]
Hi, yes it is, look up the `--filelist` option in the README, it enables docking of a batch of molecules. Compiling with `OVERLAP=ON` has performance benefits.

Other useful options are `--contact_analysis 1` and  `--devnum all`.

**Comment by apaydinemre** [comment]
Thank you very much for your help. Finally I would like to ask you this, I managed to install Autodock GPU, I want to start virtual screening but I think I need to create map files. Do I need to create a separate map file for my protein with each ligand? Is there a way to do this automatically? I don't know anything about map files as I have only done docking with Vina before. I would be very grateful if you could help me.

**Comment by diogomart** [comment]
See here: https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#optional-generating-affinity-maps-for-autodock-ff

Autogrid can be downloaded at https://autodock.scripps.edu/download-autodock4/

**Comment by apaydinemre** [comment]
Thank you so much!
