### ISSUE TITLE
How to get the docking result with various conformation. 

### ISSUE THREAD

**Issue by SejeongPark8354** [ccsb-scripps/AutoDock-GPU#246]
I'm currently conducting virtual screening much more efficiently thanks to your amazing development work, for which I'm very grateful. I have a question regarding my use of AutoDock-GPU.

Currently, I'm generating random conformers using rdkit and then performing UFF optimization before using them as input for AutoDock-GPU. Sometimes, the molecule conformations I obtain from the AutoDock-GPU docking results seem too limited.

Are there any settings changes or other approaches within AutoDock-GPU I could try, besides using a variety of conformations as input? Any advice you could provide on this matter would be greatly appreciated.

**Comment by diogomart** [comment]
Hello, I suggest:
```--nrun 256 --nev 64000 --rmstol 1.0```

**Comment by SejeongPark8354** [comment]
Thank you for your fast response. 
I will try this.
