### ISSUE TITLE
compilation on MacOS Sonoma with Intel CPU and GPU

### ISSUE THREAD

**Issue by lassancejm** [ccsb-scripps/AutoDock-GPU#247]
Hi, 
I would like to compile AutoDock-GPU on a laptop which runs MacOS Sonoma (14.0) and is equipped with a 2.3 GHz Quad-Core Intel Core i7  CPU and an Intel GPU (Intel Iris Plus Graphics 1536 MB). As OpenCL is deprecated, I am a bit lost regarding the compilation steps. 
Thanks for your insights!

**Comment by atillack** [comment]
@lassancejm I just upgraded to Sonoma here to test and fortunately OpenCL is still working. After installing the X Code command line tools, I used Homebrew to install a newer version of LLVM (`brew install llvm`) which supports OpenMP but you should be good with running `make DEVICE=GPU NUMWI=128`.

**Comment by lassancejm** [comment]
Thanks a lot for looking into this @atillack ! Compilation and test run completed fine with your instructions.
