### ISSUE TITLE
about the error

### ISSUE THREAD

**Issue by c00jsw00** [ccsb-scripps/AutoDock-GPU#249]
Dear Sir,
I got the error  as shown below, but I can succeed with the adgpu-v1.5.3_linux_ocl_128wi. Could you tell me how to fix it ?
Thanks 
YT 

c00jsw00@localhost:~/autodock/x86_64Linux2/src/bin/content> ../autodock_gpu_128wi -C 1 --import_dpf receptor.reactive_config --flexres receptor_flex.pdbqt -L Nirmatrelvir.pdbqt
AutoDock-GPU version: 00e3113dd11a6bd12bab4cf8a7ee3f88e3f197c1-dirty

Running 1 docking calculation (contact analysis cutoffs: R=2.1 Å, H=3.7 Å, V=4.0 Å)

Cuda device:                              NVIDIA GeForce RTX 4090
Available memory on device:               23827 MB (total: 24214 MB)

CUDA Setup time 0.582589s

Running Job #1
    Using heuristics: (capped) number of evaluations set to 5210753
    Local-search chosen method is: ADADELTA (ad)
SetKernelsGpuData copy to cData failed invalid device symbol
autodock_gpu_128wi: ./cuda/kernels.cu:130: void SetKernelsGpuData(GpuData*): Assertion `0' failed.
Aborted (core dumped)

**Comment by atillack** [comment]
@c00jsw00 When compiling for Cuda you need to specify the GPU target architecture, in the case of the 4090 this is compute architecture 8.9 - so compiling with `make DEVICE=GPU NUMWI=128 OVERLAP=ON TARGETS="89"` should fix the above error.
