### ISSUE TITLE
atom types: HS, NS, OS

### ISSUE THREAD

**Issue by chaninpark0806** [ccsb-scripps/AutoDock-GPU#251]
I don't understand the 3 atom types HS, NS, OS.

Can you tell me what they look like in smilies code?

**Comment by diogomart** [comment]
We are not using these types, at least not anymore. They were used for non-directional H-bond potentials (the "S" stands for spherical I think). The SMILES would be the same as for the directional counterparts HD, NA, OA. [Here are the SMARTS patterns](https://github.com/forlilab/Meeko/blob/c4d06955d2101f73991de37571a1112cde7d4f49/meeko/data/params/ad4_types.json) to match these types. Note that the last SMARTS to match, going down the list, takes over preceding matches, which happens often for nitrogen, which is typed as NA first but can loose its H-bonding trait by being typed with N afterwards.
