### ISSUE TITLE
Missing centre grid co-ordinates and size_x, size_y and size_z value in 140 complex dataset to apply for Autodock Vina

### ISSUE THREAD

**Issue by srilekha1993** [ccsb-scripps/AutoDock-GPU#256]
As vina need the center grid co-ordinates and size_x,size_y,size_z values but the dataset only contains grid maps. Is there any way to evaluate these co-ordinates?

**Comment by rwxayheee** [comment]
Hi @srilekha1993, what kind of grid map files do you have access to? You can get the center coordinates and the dimensions from both the .map and .fld files generated from autogrid, if that helps. Open them in a text editor and you should be able to find them at the beginning of these files

**Comment by srilekha1993** [comment]
@rwxayheee Thanks a lot for this information

**Comment by srilekha1993** [comment]
@rwxayheee I have tried with few of the ligands for Vina GPU not able to run any of the example using the given co-ordinates and dimensions
The map file looks like below
<img width="331" alt="protein_S_map" src="https://github.com/ccsb-scripps/AutoDock-GPU/assets/36096932/a803a816-8dc3-4e6a-8603-ec64c234df49">
The config file looks like below
<img width="396" alt="5wlo_config" src="https://github.com/ccsb-scripps/AutoDock-GPU/assets/36096932/f8ca8e70-10a7-4ad2-a08b-5a6fb924f302">

After running Autodock vina its showing the following error
<img width="960" alt="5wlo_error" src="https://github.com/ccsb-scripps/AutoDock-GPU/assets/36096932/b7d72a5a-4ffe-492c-a65a-bfaadc3525c7">
Please have a look and let me know how to resolve it

**Comment by rwxayheee** [comment]
@srilekha1993 `size_x` `size_y` `size_z` are lengths (in Å), so their values = `NELEMENTS` * `SPACING` = 50 * 0.375 = 18.75 could you try that? 

18x18x18 can create a box for the ligand in 5WLO if centered at the binding site. 50x50x50 can be enough to encompass the entire protein (which may or may not be what you want)

**Comment by srilekha1993** [comment]
Thanks a lot @rwxayheee. It worked now
