### ISSUE TITLE
Boron atoms in AD4.1_bound.dat

### ISSUE THREAD

**Issue by serenafrancisco** [ccsb-scripps/AutoDock-GPU#258]
Hello! I am using AutoDock-GPU for virtual screening, I prepared my receptor as it follows:

1. Generated PDBQT file from PDB using ADT GUI (added polar H, computed Kollman charges and then spread charge deficit);
2. At this point, from terminal, I launched this command: `python3 write-gpf.py rec.pdbqt -b box_size.txt --mapprefix rec`;
3. On the GPF created above, I added the following line at the top: `parameter_file AD4.1_bound.dat`, where AD4.1_bound.dat was modified by adding B atom parameter at the bottom (atom_par  B 3.84    0.155    29.6478     -0.0015    0.0 0.0 0   -1  -1  0).
4. Launched `autogrid4 -p rec.gpf -l rec.glg` to generate grid maps for each atom type in the ligand, and got these files in my directory:
- rec.A.map
- rec.Br.map
- rec.C.map
- rec.Cl.map
- rec.d.map
- rec.e.map
- rec.F.map
- rec.HD.map
- rec.I.map
- rec.maps.fld
- rec.maps.xyz
- rec.N.map
- rec.NA.map
- rec.OA.map
- rec.P.map
- rec.S.map
- rec.SA.map

Then I ran AutoDock-GPU in batch mode (command `autodock_gpu_128wi --filelist path/to/ligands.txt --xmloutput 0 --derivtype OX=OA > my.log`). 

Now, I think I didn't get how to properly use this AD4.1_bound.dat, as Boron atoms keep giving me problems (Error: No map file specified for atom type B in fld and no derived type (--derivtype, -T) either). 

I would really appreciate any corrections/advice to the protocol, also regarding the PDBQT preparation. 
Thank you very much!

**Comment by diogomart** [comment]
Hello,
option `ligand_types` in the `.gpf` file determines which maps autogrid will write. These are complemented by `map` lines in the same order as the atom types in `ligand_types`.

**Comment by serenafrancisco** [comment]
Thank you, it worked!
