### ISSUE TITLE
autodock gpu issue

### ISSUE THREAD

**Issue by 123TRAINTZ** [ccsb-scripps/AutoDock-GPU#271]
I get the following error when using autodock gpu, how can I solve it?

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN128WI   -cl-mad-enable
OpenCL device:                           NVIDIA GeForce RTX 4060
Error: System consists of too many atoms.'
       Maximum number of atoms is 256.

Error in parse_liganddata, stopped job.

Error in setup of Job #1
Run time of entire job set (1 file): 0.066 sec
Processing time: 0.000 sec

The job was not successful.

**Comment by diogomart** [comment]
AutoDock-GPU is optimized for docking small molecules, say roughly 20 atoms on average, 256 atoms is far larger than any molecule we tested it with. What are you trying to dock?

**Comment by 123TRAINTZ** [comment]
> AutoDock-GPU is optimized for docking small molecules, say roughly 20 atoms on average, 256 atoms is far larger than any molecule we tested it with. What are you trying to dock?

Hello, I want to use autodock gpu to dock a 14kda protein and a 100 base DNA.Tried to use gpu because it is slow to use vina but it suggests that the maximum is only 256 atoms.

**Comment by diogomart** [comment]
That's not a job for either autodock-gpu or vina. I'd suggest looking into software designed for that purpose.

**Comment by 123TRAINTZ** [comment]
> 这不是 autodock-gpu 或 vina 能胜任的工作。我建议研究一下为此目的而设计的软件。

okay,thanks!
