### ISSUE TITLE
How to perform score-only with AutoDockGPU?

### ISSUE THREAD

**Issue by tcaceresm** [ccsb-scripps/AutoDock-GPU#278]
Hi everyone!
I was wondering how to perform only the scoring of the already coupled pose with AD-GPU. I can do it with the CPU version of AD4, using a DPF file with the epdb keyword. I tried using the same DPF, but AD-GPU fails.
Any clues?
Thanks

**Comment by diogomart** [comment]
Hello, it's `--rlige 1`, which asks it to print the energy of the reference ligand. The reference ligand is the input ligand by default, but you can use `--xraylfile` to set a different ligand file as reference. The docking will still run.

**Comment by tcaceresm** [comment]
Thanks, working as expected. (Perhaps it would be useful to avoid perform docking)

**Comment by diogomart** [comment]
yeah that makes sense, one is either interested in docking or in just scoring an existing pose. If the unnecessary docking is  taking a significant amount of time, consider `--nev 0` or `--nev 1` or `--nrun 0` or `--nrun 1` or `--ngen 0` or `--ngen 1`. I didn't try these, but they will probably stop the docking nearly immediately.
