### ISSUE TITLE
Problem with a drug containing an Si atom type

### ISSUE THREAD

**Issue by xavgit** [ccsb-scripps/AutoDock-GPU#280]
Hi,
I 've made a docking with Vina and ADGPU for the same set of drugs.
With Vina I do not receive error whereas with ADGPU for ten molecules
I receive error.
Each of these drugs in the last field have one or more Si.

It possible to fix this problem?

The following is an example of a molecule giving problem with ADGPU.

[DB11267.pdbqt.txt](https://github.com/user-attachments/files/17996826/DB11267.pdbqt.txt)

Thanks.

Saverio

**Comment by diogomart** [comment]
Hi,
Can you post the error? I'm guessing it's missing the grid map. If that's the case, running autogrid with the `.gpf` file written by meeko's v0.6.1 `mk_prepare_receptor.py` should fix it.

**Comment by xavgit** [comment]
Hi,
thanks.

I've collected the DBxxxxx giving problems in a directory.
The following is an example of the commands to make the docking:
Processing  ./DB05806.pdbqt
/home/xxxx/sources/mgltools_x86_64Linux2_1.5.7/bin/pythonsh prepare_gpf4.py -l ./DB05806.pdbqt -r receptor.pdbqt -p gridcenter=51.70,64.50,83.10 -p npts=60,68,68 
/home/xxxx/sources/ADFRsuite-1.1dev/bin/autogrid4 -p receptor.gpf -l receptor.glg
/home/xxxx/sources/AutoDock-GPU-develop/bin/oclgpu_numwi_256/autodock_gpu_256wi -x 0 --ffile receptor.maps.fld --lfile ./DB05806.pdbqt --nrun 128 -N ./docking_results/DB05806_docking_res_ad4_sf --gbest 1 -psize 450 > ./docking_results/DB05806_docking_res_ad4_sf.log 2>&1
rm *.fld *.xyz *.map *.gpf *.glg

The following is the corresponding output:

Processing  DB05806.pdbqt
setting PYTHONHOME environment

/home/xxxx/sources/ADFRsuite-1.1dev/bin/autogrid4: ERROR:  unknown ligand atom type Si
add parameters for it to the parameter library first!
rm: cannot remove '*.map': No such file or directory

The following is the content of the log: file DB05806_docking_res_ad4_sf.log
AutoDock-GPU version: v1.6-release

Running 1 docking calculation

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN256WI   -cl-mad-enable
OpenCL device:                           NVIDIA GeForce RTX 2080 Ti
(Thread 30 is setting up Job #1)
Error: Grid map does not contain an (e)lectrostatics map.

Error in get_gridinfo, stopped job.

Error in setup of Job #1
Run time of entire job set (1 file): 0.144 sec
Processing time: 0.000 sec

The job was not successful.

Thanks.

Saverio
[DB05806.pdbqt.txt](https://github.com/user-attachments/files/17998690/DB05806.pdbqt.txt)

**Comment by diogomart** [comment]
Yeah, it's an autogrid error:
>/home/xxxx/sources/ADFRsuite-1.1dev/bin/autogrid4: ERROR: unknown ligand atom type Si

If you use meeko to prepare the receptor with `-g` option it will tell you how to run autogrid with parameters for Si

**Comment by diogomart** [comment]
https://meeko.readthedocs.io

**Comment by xavgit** [comment]
Hi,
ok.
Where I can find the parameter for Si?

Thanks.

Saverio

**Comment by diogomart** [comment]
It's written by meeko's mk_prepare_receptor.py to a file when ran with -g. Really, you should use it. But anyway, they are [here](https://github.com/forlilab/Meeko/blob/07a38f8bac4aa9eef4ef30aa8e67475b15d517aa/meeko/gridbox.py#L159)

**Comment by xavgit** [comment]
Hi,
thanks.
Sorry for the misunderstanding.

Saverio
