### ISSUE TITLE
Problem with:Error: No map file specified for atom type H in fld and no derived type (--derivtype, -T) either.

### ISSUE THREAD

**Issue by xavgit** [ccsb-scripps/AutoDock-GPU#282]
Hi,
having a receptor , rep.c1.pdb , and a ligand , DB05806 , I've used the following commands:

$ mk_prepare_receptor.py --read_pdb rep.c1.pdb -o receptor -p -g --box_center 51.70 64.50 83.10 --box_size 22.50 25.50 25.50 
/home/xxxx/.local/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(

Files written:
            receptor.pdbqt <-- static (i.e., rigid) receptor input file
boron-silicon-atom_par.dat <-- atomic parameters for B and Si (for autogrid)
              receptor.gpf <-- autogrid input file
          receptor.box.pdb <-- PDB file to visualize the grid box

$ /home/xxxx/sources/ADFRsuite-1.1dev/bin/autogrid4 -p receptor.gpf -l receptor.glg  
$ ls -lhtr
total 44M
-rwxrwxr-x 1 xxxx xxxx 5,9K giu 14  2011 prepare_gpf4.py
-rw-r--r-- 1 xxxx xxxx 809K set 19 16:59 rep.c1.pdb
-rwxrwxr-x 1 xxxx xxxx 1,4K ott  3 16:18 analyze_docking_res.py
-rw-rw-r-- 1 xxxx xxxx 5,4K dic  3 20:35 DB16143.pdbqt
-rw-rw-r-- 1 xxxx xxxx 7,0K dic  3 20:35 DB11585.pdbqt
-rw-rw-r-- 1 xxxx xxxx  646 dic  3 20:35 DB11343.pdbqt
-rw-rw-r-- 1 xxxx xxxx 4,9K dic  3 20:35 DB11267.pdbqt
-rw-rw-r-- 1 xxxx xxxx  362 dic  3 20:35 DB11132.pdbqt
-rw-rw-r-- 1 xxxx xxxx 5,6K dic  3 20:35 DB05806.pdbqt
-rw-rw-r-- 1 xxxx xxxx 6,0K dic  3 20:35 DB12384.pdbqt
-rw-rw-r-- 1 xxxx xxxx 4,7K dic  3 20:35 DB11244.pdbqt
-rw-rw-r-- 1 xxxx xxxx 2,6K dic  3 20:35 DB03452.pdbqt
-rw-rw-r-- 1 xxxx xxxx 2,0K dic  3 20:35 DB02265.pdbqt
drwxrwxr-x 2 xxxx xxxx 4,0K dic  6 14:06 docking_results
-rwxrwxr-x 1 xxxx xxxx 1016 dic  6 14:11 ad4gpu_docking_with_log.py
drwxrwxr-x 2 xxxx xxxx 4,0K dic  6 17:07 old_stuff
-rw-rw-r-- 1 xxxx xxxx 495K dic  6 17:36 receptor.pdbqt
-rw-rw-r-- 1 xxxx xxxx  681 dic  6 17:36 receptor.gpf
-rw-rw-r-- 1 xxxx xxxx  915 dic  6 17:36 receptor.box.pdb
-rw-rw-r-- 1 xxxx xxxx  142 dic  6 17:36 boron-silicon-atom_par.dat
-rw-rw-r-- 1 xxxx xxxx 3,3K dic  6 17:37 README
-rw-rw-r-- 1 xxxx xxxx   42 dic  6 17:48 receptor.maps.xyz
-rw-rw-r-- 1 xxxx xxxx 2,9K dic  6 17:48 receptor.maps.fld
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.S.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.Si.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.SA.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.P.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.OA.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.N.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.NA.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.I.map
-rw-rw-r-- 1 xxxx xxxx 1,8M dic  6 17:48 receptor.HD.map
-rw-rw-r-- 1 xxxx xxxx 5,3M dic  6 17:48 receptor.glg
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.F.map
-rw-rw-r-- 1 xxxx xxxx 1,5M dic  6 17:48 receptor.e.map
-rw-rw-r-- 1 xxxx xxxx 1,6M dic  6 17:48 receptor.d.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.C.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.CL.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.Cl.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.BR.map
-rw-rw-r-- 1 xxxx xxxx 2,1M dic  6 17:48 receptor.Br.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.B.map
-rw-rw-r-- 1 xxxx xxxx 2,0M dic  6 17:48 receptor.A.map

/home/xxxx/sources/AutoDock-GPU-develop/bin/oclgpu_numwi_256/autodock_gpu_256wi -x 0 --ffile receptor.maps.fld --lfile ./DB05806.pdbqt --nrun 128 -N ./docking_results/DB05806_docking_res_ad4_sf --gbest 1 -psize 450 > ./docking_results/DB05806_docking_res_ad4_sf.log 2>&1 

The log file content is:
AutoDock-GPU version: v1.6-release

Running 1 docking calculation  

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN256WI   -cl-mad-enable
OpenCL device:                           NVIDIA GeForce RTX 2080 Ti
(Thread 26 is setting up Job #1)
Error: No map file specified for atom type H in fld and no derived type (--derivtype, -T) either.

Error in parse_liganddata, stopped job.

Error in setup of Job #1
Run time of entire job set (1 file): 0.156 sec
Processing time: 0.000 sec

The job was not successful.

I've also issued the following to better understand the "Error in parse_liganddata, stopped job.":

$ awk '{ print $12=="H" }' receptor.pdbqt | grep 1 | wc -l
0
$ awk '{ print $12=="H" }' DB05806.pdbqt | grep 1 | wc -l
27

Therefore I'm guessing that the error arise from the ligand mk_prepared keeping the Hs.

Any suggestions to overcame the error?

Thanks.

Saverio

**Comment by diogomart** [comment]
Hello,
That's correct, the "H" types in the ligand are not expected when running mk_prepare_ligand.py with default parameters. The option that controls that behavior is `--merge_these_atom_types`, and by default it is a list with `["H"]`. If you ran the script with `--merge_these_atom_types` without specifying any types, then `merge_these_atom_types` becomes an empty list and you will see "H" types in the ligand PDBQT.

**Comment by diogomart** [comment]
link to the relevant part of the docs in case it's helpful
https://meeko.readthedocs.io/en/release/lig_prep_advanced.html#merging-hydrogens-or-not

**Comment by xavgit** [comment]
Hi,
ok , I've read the link.
The ligands , about 10000, all have been mk_prepared with 
mk_prepare_ligand.py  -v  --rigid_macrocycles  --merge_these_atom_types <empty list> -i .....   -o ....
and then I've used with ADGPU and Vina having problem only with ADGPU for ten ligands with Si atom type.
I don't know if this, keeping the H, has been a right choice.
Having the H not merged can be a problem for the docking results?
What I can do to overcame the error: 'Error: No map file specified for atom type H' for the ten ligands with ADGPU ?

Thanks.

Saverio

**Comment by diogomart** [comment]
For the AD4 scoring function, which autodock-gpu uses, you want to merge the H, which means you need to run mk_prepare_ligand.py again without the `--merge_these_atom_types` option.

For Vina, it does not matter, H are simply ignored. Even HD are used only to assign H-bonding donor capabilities to heavy atoms, but HD don't participate in any interactions. Having H probably makes Vina run a little slower, but that's all.

**Comment by xavgit** [comment]
Hi,
OK.

Thanks.

Saverio

**Comment by diogomart** [comment]
You're welcome
