### ISSUE TITLE
Anchored Docking information

### ISSUE THREAD

**Issue by tcaceresm** [ccsb-scripps/AutoDock-GPU#283]
Hi there!
Where can I find information about Anchored Docking? I found this link [https://github.com/ccsb-scripps/AutoDock-GPU/wiki/](url) in other posts but it looks like is not available anymore.
Thanks in advance

**Comment by diogomart** [comment]
Sorry about that, i took it down because it was outdated with respect to meeko v0.6. I'll upload the new one soon to meeko readthedocs and notify here. Could you post the links you know of that point to the now-removed wiki page?
Thanks!

**Comment by tcaceresm** [comment]
Oops didn't notice that the link was wrong.
https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Anchored-docking
This is the link that I found. Sorry about the formatting but I'm in my phone

**Comment by diogomart** [comment]
Oh I meant the pages that still point to this link, so I can edit them and point to the new link when that is up. But don't worry if you don't have them handy. Thanks anyway :-)

**Comment by rwxayheee** [comment]
Hi @diogomart 
It seems to be from a comment: https://github.com/ccsb-scripps/AutoDock-GPU/issues/204

If OP found it from other posts in this repository, @tcaceresm please feel free to clarify if I’ve misunderstood!

**Comment by tcaceresm** [comment]
@rwxayheee that's correct, also this issue in Vina [https://github.com/ccsb-scripps/AutoDock-Vina/issues/280](url)

**Comment by diogomart** [comment]
@tcaceresm just put it up here: https://meeko.readthedocs.io/en/docs_anchored_tutorial/tutorial_anchored.html

We still need to figure out where to put the scripts to add the bias potential and insert into the FLD file. They might end up in a `mk_grid_things.py` script. Meanwhile, here they are in a zip file: 
[anchored_docking_scripts.zip](https://github.com/user-attachments/files/18169725/anchored_docking_scripts.zip)

**Comment by tcaceresm** [comment]
Cool! I'm gonna test it soon. Thanks for your quick response! I'll close this issue
