### ISSUE TITLE
Parsing of fld file possibly pointless

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#42]
From @diogo.martins:

The fld file (input arg `-ffile`) is [parsed](https://git.esa.informatik.tu-darmstadt.de/docking/ocladock/blob/96a0f0f595ec1c61c6f2f4759543a358f4657d26/host/src/processgrid.cpp#L68) to get the following data:

1.  spacing, grid center, and grid size
2.  the prefix for map files

The fld file explicitly declares an association between atom types and map files. These are currently ignored by ocladock.  

It could be more intuitive if the `-ffile` argument was replaced by a `-mapprefix` argument. The grid center, size and spacing would then be parsed from the map files.

Note: this is very low priority.

**Comment by diogomart** [comment]
Current behavior is satisfactory, see https://github.com/ccsb-scripps/AutoDock-GPU/pull/90
