### ISSUE TITLE
VS: avoid loading maps every time for each ligand

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#61]
It was mentioned by @diogo.martins :

> In the future, to make virtual screening faster, we should avoid loading maps every-time for each ligand. Instead, we load maps once and dock thousands of ligands. If we do that, pace speedups are probably more informative than runtime speedups.

This idea was implemented in [idock, derived from Vina](https://ieeexplore.ieee.org/document/6217214).

**Comment by atillack** [comment]
Implemented with PR #82 and the `-filelist` option.
