### ISSUE TITLE
Early-termination criteria using E50

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#62]
From @diogo.martins:

> ... once the program has started execution, there is no stopping criteria that effectively takes advantage of this knowledge. Stopping criteria is definitely a topic for future work, both for the LGA (`-nev`), and for the LS (`-lsit`).

**Comment by diogomart** [comment]
Heuristics for choice of search method (-lsmet) and number of evaluations (-nev) added by @atillack on commit 5e1717a2d16ce74c788e99744bb0cf6a1f86fba2

Improvement on stopping criterion: 4142473c9195e9678751c0842770896233f92de8

**Comment by diogomart** [comment]
Early termination implemented by @atillack, enable with command line option `-autostop 1`.
