### ISSUE TITLE
Strange behavior of interpolation

### ISSUE THREAD

**Issue by al42and** [ccsb-scripps/AutoDock-GPU#64]
Hello all,

I'm not sure that it causes any actual issues, but this code, repeated in a couple places, looks fishy:

We use constants to avoid interpolation outside the valid interval, but we then overwrite this value anyway with results obtained from interpolation of undefined values. Probably, these lines should have been inside the preceding `else` block?

https://github.com/ccsb-scripps/AutoDock-GPU/blob/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/device/calcMergedEneGra.cl#L1365

https://github.com/ccsb-scripps/AutoDock-GPU/blob/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/device/calcMergedEneGra.cl#L1394

**Comment by diogomart** [comment]
Thank you for pointing this out. Tested the corrected code on a single protein-ligand complex and the scores improved. I'll test on a larger scale and then merge to master.

**Comment by diogomart** [comment]
After testing on 140 protein-ligand complexes, and calculating the number of scoring function calls necessary to achieve a 50% success rate (see details [here](https://chemrxiv.org/articles/Accelerating_AutoDock4_with_GPUs_and_Gradient-Based_Local_Search/9702389)), I conclude that the search performance remains identical.

**Comment by diogomart** [comment]
Merged to master, closing now.
