### ISSUE TITLE
Make gradient point in the direction of the search box

### ISSUE THREAD

**Issue by diogomart** [ccsb-scripps/AutoDock-GPU#65]
For each translation variable, make derivative negative if x < 0, and positive if x > size_of_box. This should be done for x, y and z independently.

https://github.com/ccsb-scripps/AutoDock-GPU/blob/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/device/calcMergedEneGra.cl#L447-L449

**Comment by atillack** [comment]
It's already in the develop branch, plan is to add things to master for the next "release" :-)

**Comment by atillack** [comment]
As it turns out, this is not a good idea ... Convergence is better without it.
