### ISSUE TITLE
multi-gpu support?

### ISSUE THREAD

**Issue by programmab1e** [ccsb-scripps/AutoDock-GPU#66]
Autodock-GPU only seems to run on a single GPU. Is there a simple way to enable multi-GPU execution and/or assign jobs to specific GPUs?

**Comment by atillack** [comment]
Thank you for your question. Each instance currently runs on one specific GPU. If you check out the new develop branch we do now support assigning a specific GPU with the "-devnum" parameter and you even get a bit of a speedup :-)

**Comment by diogomart** [comment]
@programmab1e not sure if this is relevant for your purposes: on Linux it is possible to use GNU Parallel to coordinate the usage of multiple GPU's, with something like:

```parallel -j 8 'eval CUDA_VISIBLE_DEVICES=$(({%} - 1)) {}' < commands.txt```

where each line in `commands.txt` corresponds to one docking (one process). Using `-devnum` is probably more convenient than setting the environment variable "CUDA_VISIBLE_DEVICES".

**Comment by atillack** [comment]
@programmab1e PR #139 which will likely turn into a new release soon includes support for using multiple GPUs on a given machine when used in conjunction with `make OVERLAP=ON` and when doing a virtual screening on multiple ligand files (i.e. specified with `--filelist`).

**Comment by atillack** [comment]
@programmab1e Version 1.5 with multi-GPU support is out. When compiled with `OVERLAP=ON`, one can use `-D all` to use all available devices when docking multiple ligands. It is also possible to only use certain GPUs by specifying them with a comma-separated list, for example `-D 1,2,3`.
