### ISSUE TITLE
Is there a script converting protein.pdb to <protein>.maps.fld?

### ISSUE THREAD

**Issue by pshen1230** [ccsb-scripps/AutoDock-GPU#67]
Hello I'm new to structural biology.
I know you can use autogrid to select the bounding box and generate the .maps.fld, but I've been unable to figure out the workflow.
Also for preliminary screening I want to search the whole protein without specifying a bounding box.
Is there a script for converting protein.pdb to <protein>.maps.fld?

Thanks!

**Comment by diogomart** [comment]
Hi!

The ".maps.fld" file is created by autogrid. The grid dimensions are defined by the user in the grid parameter file (.gpf). This ".gpf" file is needed to run autogrid.

To search the whole protein you need to define a large grid enclosing the protein, or multiple smaller boxes at different sites.

For more information on how to run autogrid see https://www.ncbi.nlm.nih.gov/pubmed/27077332

**Comment by L30nardoSV** [comment]
Closing it as it is related to baseline AutoDock.
