### ISSUE TITLE
Add support for parsing dpf

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#69]
Docking parameters are specified via command-line arguments as explained in the [documentation](https://github.com/ccsb-scripps/AutoDock-GPU/tree/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b#supported-arguments).

Supporting alternatively the parameters entry via .dpf (docking parameter file) could be useful for those used to run the original AutoDock.

**Comment by atillack** [comment]
In terms of actually supporting the dpf file and syntax from AD4 this is likely not where we're heading... Using an input file instead of command line parameters on the other hand is not a bad idea.
