### ISSUE TITLE
Use OpenCL C++ wrapper API

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-GPU#70]
So far, AutoDock-GPU uses the OpenCL C API. To reduce verboseness, _custom_ wrapper functions have been defined in the [wrapcl folder](https://github.com/ccsb-scripps/AutoDock-GPU/tree/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/wrapcl), and invoked in the [host code](https://github.com/ccsb-scripps/AutoDock-GPU/blob/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/host/src/performdocking.cpp#L177).

To further increase code legibility, the [OpenCL C++ wrapper API](https://www.khronos.org/registry/OpenCL/specs/opencl-cplusplus-1.2.pdf) could be used. With such C++ wrapper, no more code within the [wrapcl folder](https://github.com/ccsb-scripps/AutoDock-GPU/tree/9e18c63a709abb3bc79a0fa026ee33bf02d85e9b/wrapcl) will be required.

**Comment by atillack** [comment]
I am a bit meh on this but if you really see a big advantage to this and want to PR it I'll support it...
