### ISSUE TITLE
problem with native_powr in OpenCL on macOS?

### ISSUE THREAD

**Issue by ascheinb** [ccsb-scripps/AutoDock-GPU#73]
native_powr (which is used for exponents in the openCL code) returns a completely bogus answer on my laptop (macOS Mojave 10.14.6). I detected the problem on lines 434-435 in device/calcenergy.cl, but I didn't spend much time trying to figure out why, since I was removing OpenCL anyway. (So I just switched it to use pow() for testing.) Maybe there was a type mismatch or something. I guess there's not much to be done about this, but thought y'all should know!

**Comment by atillack** [comment]
Thank you Aaron, good observation. This is really interesting and we haven't seen this behavior on macOS Catalina with neither the integrated graphics card nor an external AMD card (my development machine during lockdown) ... Could you test if the main branch has the same issue on your machine?

**Comment by L30nardoSV** [comment]
Similar to @atillack, I haven't observed that behavior of `native_pow` on AMD, Nvidia, nor Intel CPUs. 

It sounds like a bug on that macOS OpenCL driver ...
