### ISSUE TITLE
Bug in gradient calculation

### ISSUE THREAD

**Issue by ascheinb** [ccsb-scripps/AutoDock-GPU#77]
In device/calcMergedEneGra.cl, in the rotation-related gradients section:

`double torque_length = sqrt(pow(torque_rot.x,2) + pow(torque_rot.y,2) + pow(torque_rot.z,2));`

`torque_rot` sometimes turns out to be 0. It is usually only approximately 0 because of rounding error so it's not a problem. Occasionally it is exactly 0, which means that `torque_length` is 0, and everything else in this section becomes NaN because things get divided by `torque_length`. So then the gradient_genotype for [3], [4], and [5] come back as NaN, the next energy evaluation is a NaN, and since NaN > best_energy is false, the gradient descent simply stops, but with no detectable bugs outside of that.

Suggestion would be to simply add an epsilon to the `torque_rot` calculation.

**Comment by atillack** [comment]
Thank you Aaron, good catch! If the torque rotation vector is zero that means there is no net torque on the ligand and this shouldn't cause a NaN there. Fixing it right now.
