### ISSUE TITLE
How do you perform docking when you have multiple ligands ?

### ISSUE THREAD

**Issue by ideasjunk** [ccsb-scripps/AutoDock-GPU#78]

**Comment by L30nardoSV** [comment]
This has been asked also here: https://github.com/ccsb-scripps/AutoDock-GPU/issues/80#issuecomment-629980303

**Comment by debanjansen48** [comment]
any solution or advice from your end.... I am unable to any locate info @#80

**Comment by debanjansen48** [comment]
any update regarding VS using this tool?

**Comment by L30nardoSV** [comment]
@ideasjunk, @debanjansen48: 

You can use the batch file option `-filelist` to docking multiple ligands, and even multiple proteins. For more details check [README.md](https://github.com/ccsb-scripps/AutoDock-GPU#supported-arguments).

Such feature has been added recently by merging https://github.com/ccsb-scripps/AutoDock-GPU/pull/82 into the `develop` branch.
