### ISSUE TITLE
Does the program allow rotable/flexible residues in the receptor?

### ISSUE THREAD

**Issue by EcheCodeLab** [ccsb-scripps/AutoDock-GPU#81]

**Comment by diogomart** [comment]
Hello,
No, flexible residues are not supported. This is a feature that may be implemented at some point.

**Comment by EcheCodeLab** [comment]
Thanks! It would be great since AutoDock-CUDA works for NVIDIA GPUs only, and I couldn't find any similar software that supports AMD GPUs.
Great program anyways!

**Comment by atillack** [comment]
It does now with the `-flexres` option.
