### ISSUE TITLE
Read more of the .fld file!

### ISSUE THREAD

**Issue by jvermaas** [ccsb-scripps/AutoDock-GPU#84]
Lets say I was changing my grids from an original.*.map to something else, but wanted to reference the original.pdbqt. Since the .maps files are enumerated in the .fld file passed as input to AutoDock-GPU, a user might have the expectation that newly generated grids output from autogrid would be used. However, due to assumptions within processgrid.cpp (that the receptor is the basename for the map), the old grids will be used instead! This is, shall we say, non-intuitive... Would it be acceptable to store the .fld name itself rather than the receptor name? That is what autogrid actually seems to use as the basename for the map files by default.

**Comment by atillack** [comment]
Hi Josh! Thank you for the comment :-) I agree and this is probably a good time to also address #42 ...

I see two possible solutions:
1) Get rid of the fld file altogether and let -ffile (probably renamed slightly) specify the maps' base name (this is what #42 is suggesting)
2) Use the base name of the fld file as the base name for the maps (autogrid outputs them like that)...

I think 1) is probably cleaner (and the fld file has been a thorn in our side for a while). What do you think?

**Comment by jvermaas** [comment]
I totally didn't see #42 (it was early in the morning), but I really appreciate how the two paths are either to read more _or_ read less of the .fld file. :) From my understanding of the conventional workflow, autogrid makes the .fld and the maps from the .gpf. The .fld has the benefit of being the only generated file that has all the information present to uniquely point to the receptors and maps being used. Specifying the map prefix wouldn't get you a receptor pdbqt, although I suppose autodock doesn't actually need one of those, so from a technical standpoint both options would work. My inclination would be to slavishly follow whats in the .fld file, since that creates a record of what was done that is comprehensible and in a single file, but I realize that its only my opinion, and I don't know what other issues the .fld file is causing.

**Comment by atillack** [comment]
The benefit with ignoring the fld file is that you can more easily add other maps (either because you want more maps than autogrid is supporting) or because you are trying out different atom types etc ... the other thing is that you might want to rename things after map creation and while you can certainly edit the fld file (the receptor name) this is also an additional step.

In any case, the fld file is a bit superfluous in my opinion as the actually relevant info (for autodock) is in the map files anyway and the gpf input file to autogrid on the other side provides you with the other info that's relevant to recreate the maps. So the fld file is kind of in between but not really anywhere at the same time.

**Comment by jvermaas** [comment]
Ok. I think either option is fine, I just wanted some input from others before I go off and add code to read more of the .fld file. If the consensus is to ditch the fld, that's cool, I just need to know what areas of the code would all need to change, since it took alot of grepping to find why my .fld changes weren't being reflected in the results, and most users won't know what they did wrong.

**Comment by diogomart** [comment]
Hi all,

I like the idea of ditching the .fld and specifying the maps' base name directly.

@jvermaas thank you for bringing this up.

**Comment by atillack** [comment]
One wrinkle with removing the fld file is that it would require a syntax change for the batch file (no .fld to look for means a specifier wether a line is a grid name or a resnam) ... While this is something that may slowly happen to add more features to it, it's not a good idea to rush right now ...

Based on that, I will likely just use the base name of the fld file as the map base name (as the fld base name at creation time is also the base name of the maps)... This seems like the least invasive change right now.
