### ISSUE TITLE
Doc seems to be incorrect for filelist

### ISSUE THREAD

**Issue by asedova** [ccsb-scripps/AutoDock-GPU#88]
Hey in the new filelist doc the order seems to be inverted. Unless the code has been changed, we have been using ligand output name first, followed by path to pdbqt

**Comment by atillack** [comment]
When you look in the code, you will find it literally just scans each line for .fld for the grid files, .pdbqt for the ligand, and everything else is resnam... So currently, the order of those lines relative to each other is not important.

**Comment by atillack** [comment]
That said, I appreciate you going over the docs as this sometimes can end up a bit too low on the priorities list ;-) Thanks, Ada!
