### ISSUE TITLE
-filelist execution

### ISSUE THREAD

**Issue by debanjansen48** [ccsb-scripps/AutoDock-GPU#89]
thank you for the update. But i am unable to run batch operation please help me out.

in the working directory i put my protein information including map.fld file in a folder name protein and all ligands in pdbqt for mat in a folder lig then issued the command given bellow

/ADT-Gpu/batch$ ./autodock_gpu_256wi  -ffile ./protein/  -filelist ./lig

Error: ligand pdbqt file was not defined. Use -lfile argument!

how to resolve.

**Comment by L30nardoSV** [comment]
Hi @debanjansen48,

First, the arguments for `-ffile` and `-filelist` are files, **not folders**, as you specified above.

Second, please follow the format guidelines suggested here: https://github.com/ccsb-scripps/AutoDock-GPU#supported-arguments

Basically, for the `-filelist <MYFILE>` option you need to specify a `<MYFILE>` with this format:

```
./receptor1.maps.fld
./ligand1.pdbqt
Ligand 1
./receptor2.maps.fld
./ligand2.pdbqt
Ligand 2
./receptor3.maps.fld
./ligand3.pdbqt
Ligand 3
```

**Comment by debanjansen48** [comment]
respected sir

As I understood I have to write a command (as per you mentioned)

in terminal       $  ./autodock_gpu_256wi ./receptor1.maps.fld
./ligand1.pdbqt Ligand 1 ./receptor2.maps.fld ..........

and so on for 1 million ligands?

you mentioned receptor1 receptor 2 etc.... but I have only 1 receptor and
1million pdbqt file...

Plz help

**Comment by L30nardoSV** [comment]
Hi @debanjansen48,

No, basically you have to **create a file** (e.g., `MYFILE`) were you add the list of receptors, ligands and name for the output of each docking. Using this file, you do not have to specify the molecules within the command.

If you have **a single** receptor and **many** ligands, the contents of your `MYFILE` can be like this:

```
./receptor.maps.fld
./ligand1.pdbqt
Ligand 1
./ligand2.pdbqt
Ligand 2
...
<more ligands and names for the .dlg files>
...
```

Then, you can run that with this command:

```bash 
$  ./autodock_gpu_256wi -filelist MYFILE <other options>
```
`<other options>` can be: 
* `-nrun`, `-lsmet`, etc
* but not `-ffile`, `-lfile` (as molecules are already specified in `MYFILE`)

Hope this helps!

**Comment by debanjansen48** [comment]
i prepared MYFILE (list_lig.txt) as follows
*****************************************
./6lu7.maps.fld
./NPC1486.pdbqt
Ligand 1
./NPC1704.pdbqt
Ligand 2
./NPC1744.pdbqt
Ligand 3
./NPC1811.pdbqt
Ligand 4
./NPC1886.pdbqt
Ligand 5
./NPC1991.pdbqt
Ligand 6
******************************
then issued the command
autodock_gpu_256wi -filelist list_lig.txt  -nrun 5 -lsmet

(the directory possess the file* 6lu7.maps.fld*)

but it returns
*Error: grid fld file was not defined. Use -ffile argument!*


*"(base) dLab@deb:~/Desktop/ADT-Gpu/batch/ligs$ autodock_gpu_256wi
-filelist list_lig.txt  -nrun 5 -lsmetError: grid fld file was not defined.
Use -ffile argument!"*

**Comment by diogomart** [comment]
@debanjansen48 did you compile AutoDock-GPU yourself? If you are using the precompiled binaries that explains the problem, because they were compiled before the -filelist feature was implemented.

**Comment by debanjansen48** [comment]
I compiled before as per the instruction
"
https://github.com/ccsb-scripps/AutoDock-GPU/issues/80#issuecomment-629980303
"

That works nicely for me during single ligand docking

**Comment by debanjansen48** [comment]
yes....I newly compiled it as per the previous instructions. and used the
command

./autodock_gpu_256wi -filelist lig_list.txt

it works... Thanks.. thanks...
I want to know
is it necessary to put "./" before every ligand and Ligand 1 or 2 etc after
every line

Actually i created the list by

ls  >> lig_list.txt

then in the lig_list.txt file manually i put  "./"

sorry to say I am not a linux expert.... in order to discover "ls >>
lig_list.txt" i just consumes huze time..
that is why asking you sir.
is there any other way to make it easy..

**Comment by diogomart** [comment]
Glad to know it works for you.

You can try without './' and see if it works or not. If not, then `for x in $(ls); do echo './'$x; done > list.txt` should do the trick.

**Comment by debanjansen48** [comment]
sir,
IT WORKS.........

without "./" it works.....

This program is extremely 1st.......I am so happy......certainly it will
make my life easy........wooaooo....... just docked 50 ligs within 2 to
3min with -nrun 10 options
No other tools can bit it i sware ....my legs are moderately big with more
than 5 rotatable bonds.... Other commercial and well known open source
docking tools take minimum 20min or more....

I* am sorry, but I think I should tell you.*

it generates 50 .dlg file "docking1.dlg" file.... it's a tedious job for
large library *screening to open each and every .dlg file and note down the
dock score, clustering info etc*..

is there any trick to solve that.. if u dont mistake me.

Thanks again

**Comment by diogomart** [comment]
Happy to hear you are happy with the speed! Just keep in mind that comparing the speed is meaningful only if the results are of comparable quality. 

For analyzing many files I recommend the Python language.
