### ISSUE TITLE
[CUDA] SetKernelsGpuData copy  to cData failed invalid device symbol

### ISSUE THREAD

**Issue by lpmcsn** [ccsb-scripps/AutoDock-GPU#91]
Dear all,

I have successfully installed and used OpenCL version of AutoDock GPU and now I would like to use CUDA version. So I have compiled Autodock in this way and everything went well. 
But now if I try to run AutoDock CUDA I get an error : 
```
AutoDock-GPU version: sd-tsri-301-gd3bed224db27fa4ddbcadfa0c4781892e34dc0f1

CUDA Setup time 2.529721s
(Thread 0 is setting up Job 0)
autodock_gpu_64wi: ./cuda/kernels.cu:147: void SetKernelsGpuData(GpuData*): Assertion `0' failed.

Running Job #0:
Local-search chosen method is: Solis-Wets (sw)
SetKernelsGpuData copy to cData failed invalid device symbol
```

Does anybody have an idea about this issue ? 
I have noticed that the quotes are not the same here : `Assertion `0' failed` but not sure it is relevant...

Thank you for your help !

**Comment by L30nardoSV** [comment]
Hi @lpmcsn,

We can try reproducing this error on our side, so please provide us:

* The exact comand you are using (and if you can the inputs too)
* GPU info

**Comment by lpmcsn** [comment]
Leonardo, 
For the context, Autodock is running on supercomputer using slurm.
I have not sent input files because the error is the same for every kind of protein or ligand.

* Launch (with only necessary commands)
```
#SBATCH -N 1
#SBATCH -c 12
#SBATCH --gres=gpu:1
#SBATCH --gres-flags=enforce-binding

module load gcc/7.4.0
module load cuda/10.0

srun ./bin/autodock_gpu_64wi -ffile <protein>.maps.fld -lfile <lig>.pdbqt -nrun 20

```
* GPU Info 
NVIDIA Tesla P100 NVLink optimized 
See here : https://www.nvidia.com/en-us/data-center/tesla-p100/

**Comment by lpmcsn** [comment]
* Preparation for compilation
```
module load gcc/7.4.0 cuda/10.0
 
export CUDAROOT=/apps/cuda/10.0
export GPU_INCLUDE_PATH=$CUDAROOT/include
export GPU_LIBRARY_PATH=$CUDAROOT/lib64
```
* CUDA Test
```
./test_cuda.sh
yes
```

* Compilation
```
make DEVICE=CUDA NUMWI=64
#Also tried only make DEVICE=GPU
```
[autodock_cuda_log.txt](https://github.com/ccsb-scripps/AutoDock-GPU/files/4836098/autodock_cuda_log.txt)

**Comment by L30nardoSV** [comment]
@lpmcsn 

Compilation commands you use seem OK.

If the issue happens with all inputs, then I guess this is because of a missing specific device-config.  I have no P100 GPU at hand to reproduce it, but can you try modifying the following line as follows?  (adding the number `60`)

https://github.com/ccsb-scripps/AutoDock-GPU/blob/develop/Makefile.Cuda#L18

```
TARGETS = 52 60 61 70
```

Please share the outcome.

**Comment by lpmcsn** [comment]
@L30nardoSV got good news here !
```
AutoDock-GPU version: sd-tsri-301-gd3bed224db27fa4ddbcadfa0c4781892e34dc0f1-dirty

CUDA Setup time 2.544920s
(Thread 0 is setting up Job 0)

Running Job #0:
Local-search chosen method is: Solis-Wets (sw)

Rest of Setup time 0.024663s

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************
Docking time 1.979830s


Shutdown time 0.000316s

Job #0 took 2.005 sec after waiting 3.004 sec for setup

(Thread 0 is processing Job 0)

Run time of entire job set (1 files): 5.123 sec
Savings from multithreading: -2.550 sec
Idle time of execution thread: 3.118 sec
All jobs ran without errors.
```
[autodock_cuda_log2.txt](https://github.com/ccsb-scripps/AutoDock-GPU/files/4836327/autodock_cuda_log2.txt)

All seems to be working well now.

Should I create a pull request ?

**Comment by L30nardoSV** [comment]
:smile: Glad it works! Yes, please create the PR!

**Comment by lpmcsn** [comment]
Thank you for all, I will do that!
