### ISSUE TITLE
Segmentation fault when trying to use overlapping (OVERLAP=YES)

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [ccsb-scripps/AutoDock-GPU#95]
Hello,

We are able to successfully run some docking with a file list using the `OVERLAP=NO` version of AutoDock-GPU (from current develop branch) but we are running into some issue with the `OVERLAP=YES` version.

With `OMP_NUM_THREADS=1`, the `OVERLAP=YES` version works fine. With `OMP_NUM_THREADS` is greater or equal to 2, the code crashes with a segfault as soon as a thread other than master starts processing a ligand.

 * CUDA version:
```
$ export OMP_NUM_THREADS=2
$ srun autodock_gpu_64wi -filelist batchfile -nrun 9
Running 248 jobs in pipeline mode
AutoDock-GPU version: 1e4fbbcc046eeb33c48ae023eae249477cd42cec

CUDA Setup time 0.127270s

Using 2 OpenMP threads
(Thread 0 is setting up Job 0)
(Thread 1 is setting up Job 1)

Running Job #1:
   Fields from: /.../dock/6lu7-receptor_crystal.maps.fld
   Ligands from: /.../dock/KKAA/KKAAMP002.pdbqt
srun: error: r12i7n0: task 0: Segmentation fault (core dumped)
```
  * OpenCL version:
```
$ export OMP_NUM_THREADS=2
$ srun autodock_gpu_64wi -filelist batchfile -nrun 9
Running 248 jobs in pipeline mode
AutoDock-GPU version: 1e4fbbcc046eeb33c48ae023eae249477cd42cec

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN64WI   -cl-mad-enable
OpenCL device:                           Tesla V100-SXM2-16GB

Using 2 OpenMP threads
(Thread 0 is setting up Job 0)
(Thread 1 is setting up Job 1)

Running Job #0:
   Fields from: /.../dock/6lu7-receptor_crystal.maps.fld
   Ligands from: /.../dock/KKAA/KKAAMP001.pdbqt
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #0 took 0.686 sec after waiting 0.333 sec for setup

(Thread 0 is processing Job 0)

Running Job #1:
   Fields from: /.../dock/6lu7-receptor_crystal.maps.fld
   Ligands from: /.../dock/KKAA/KKAAMP002.pdbqt
srun: error: r12i7n0: task 0: Segmentation fault (core dumped)
```

The segmentation fault seems to happen at this line:
https://github.com/ccsb-scripps/AutoDock-GPU/blob/1e4fbbcc046eeb33c48ae023eae249477cd42cec/host/src/calcenergy.cpp#L143

Any idea?

Best,
Rémi

**Comment by atillack** [comment]
@RemiLacroix-IDRIS Hi Remi, thank you for the bug report. I will see if I can reproduce it. Which compiler were you using?

**Comment by atillack** [comment]
@RemiLacroix-IDRIS I can reproduce it, on to fixing it...

**Comment by atillack** [comment]
@RemiLacroix-IDRIS The fix is merged. Please let us know if it works on your end.

**Comment by RemiLacroix-IDRIS** [comment]
@atillack: Thanks! I am currently on holidays, I will let you know when I am back on August 17th.

**Comment by RemiLacroix-IDRIS** [comment]
I can confirm the "problem" is fixed. Looking at the patch, it seems like I could just have used `OMP_STACKSIZE` environment variable, sorry I didn't think about this.

**Comment by atillack** [comment]
@RemiLacroix-IDRIS Thank you for confirming that it works for you! I didn't think about `OMP_STACKSIZE` either ;-)
