### ISSUE TITLE
Hydrated Docking

### ISSUE THREAD

**Issue by mallanos** [ccsb-scripps/AutoDock-GPU#96]
Hi,
I'm trying to run hydrated docking protocol but I got:

Error: Ligand includes atom with unknown type: A!

Same ligand works well in standard Autodock4
It is not implemented yet in GPU code or am I missing something?
Thanks
Manu

**Comment by diogomart** [comment]
Hi Manu,
Hydrated docking is implemented. Did you compile from a recent version (develop branch)? Can you send an example so we can reproduce the problem?

**Comment by mallanos** [comment]
Hi diogomart,
I've been using the master branch compiled a few months ago, now I tried with precompiled binaries from develop branch but still getting the same error.
Running the same script with non-hydrated docking works well, as well as running hydrated docking with the old Autodock4
Here I provide you an example, just run the run_hydrated.sh script inside "receptors" folder
Thanks !

[Hydrated_docking_example.zip](https://github.com/ccsb-scripps/AutoDock-GPU/files/5029703/Hydrated_docking_example.zip)

**Comment by diogomart** [comment]
Hi,
Thanks for sending the example. It runs with the current code. The precompiled binaries are outdated, so the best is to compile the latest develop branch ([see wiki for instructions](https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Guideline-for-users)). Let us know if you have any issues.

**Comment by mallanos** [comment]
Is working now 
Thank you so much for your help!

**Comment by diogomart** [comment]
Awesome!
Best regards
